### PR TITLE
Unpin and upgrade requirements.

### PR DESCRIPTION
**Pull request by robrap**

### CODE REVIEW

**Comment by robrap** [comment]
@georgebabey: I dropped the DRF related upins/upgrades.  Everything passes so far. :)
We've got e2e tests (ecommerce + WL).  If it passes that, I can just monitor errors in Production.

**Review by georgebabey — APPROVED** [review]
Nice! Glad you were able to unpin all those other ones! I'm a little concerned we're leaving DRF pinned but some like DRF-JWT unpinned. That might bite us down the road so we should try to figure out what is needed to get DRF updated in the near future.

**Comment by robrap** [comment]
@georgebabey: I could pin djangorestframework-jwt again.  But, I'm hoping our tests will let us know if we have a problem, and that we can work to unpin more, or at least upgrade DRF.

**Comment by georgebabey** [comment]
@robrap No no, I agree keeping it unpin and letting the tests know when something breaks is the way to go. Just calling out the the fact this is likely to happen with DRF pinned.

**Pull request merged**
