### PR TITLE
[SOL-1916] Category ID's not sent during coupon creation

### PR DESCRIPTION
**Pull request by iivic**
@vkaracic  @marjev  Category_ids were not set on init. Should be fixed now.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=848

**Comment by vkaracic** [comment]
Why was this happening in the first place?

**Comment by iivic** [comment]
Category_ids were not set when the page rendered. So when the save button is pressed there is nothing to send/save on that field. Adding this line 'category_ids': [defaultCategory[0].id] in the render function fixed the problem.

**Comment by marjev** [comment]
This LGTM 👍 I'm currently working on cleaning up this mess, so that won't be a problem for long. We can use this fix until then to make sure that users can create coupons without problems.

**Comment by vkaracic** [comment]
LGTM

**Pull request merged**
