### PR TITLE
Code UI - WIP

### PR DESCRIPTION
**Pull request by dsego**

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @dsego! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=431

**Comment by dsego** [comment]
Wrong target.

**Comment by clintonb** [comment]
If you are working on enrollment codes, please ensure all files and class names are labelled as such. The word "code" is too broad.

**Comment by dsego** [comment]
@clintonb I will keep that in mind. Sorry for mistakenly opening a PR here.

**Comment by clintonb** [comment]
No worries. It's nice to see you're making progress!

**Comment by vkaracic** [comment]
@clintonb is it OK to use short suffixes like 'ecodes_' and 'ec_'?

**Comment by clintonb** [comment]
I prefer to be verbose to eliminate all possibility of confusion.

**Pull request closed without merging**
