### PR TITLE
Coupon test mixin

### PR DESCRIPTION
**Pull request by vkaracic**
New `CouponMixin` test mixin for containing all helper functions for coupon tests. Currently only contains `create_coupon` helper method for creating a coupon. In the future it will have a `setUp` method which creates a default coupon category which will be needed for creating coupons.

@mjfrey @clintonb

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=573&repo=edx%2Fecommerce

**Comment by mjfrey** [comment]
@rlucioni @bderusha Can you take a look?

**Comment by clintonb** [comment]
:+1:

**Comment by bderusha** [comment]
:+1:

**Pull request merged**
