### PR TITLE
Invoice processor test cleanup

### PR DESCRIPTION
**Pull request by clintonb**
Based test on PaymentProcessorTestCaseMixin to avoid unnecessary code duplication.

### CODE REVIEW

**Comment by clintonb** [comment]
@mjfrey @jimabramson

**Comment by mjfrey** [comment]
Great, thanks.  
:+1:

**Comment by jimabramson** [comment]
sorry I missed this earlier, but LGTM!

**Comment by clintonb** [comment]
Sorry @jimabramson. I forgot that I was waiting on your review, hence my not merging over the weekend.

**Pull request merged**
