### PR TITLE
Discovery: Courses page datatable with server side processing.

### PR DESCRIPTION
**Pull request by waheedahmed**
**Note:** This is a discovery work.
Used djangorestframework-datatables to implement server side processing.

https://django-rest-framework-datatables.readthedocs.io/en/latest/quickstart.html

LEARNER-5231

**Sandbox:** https://ecommerce-datatables.sandbox.edx.org/courses/

### CODE REVIEW

**Comment by BenjiLee** [comment]
@waheedahmed Could you put up a sandbox with these changes?

**Comment by waheedahmed** [comment]
@BenjiLee Here is the sandbox link https://ecommerce-datatables.sandbox.edx.org/courses/. For now, I have configured it for courses page only.

**Comment by BenjiLee** [comment]
Looks good

**Comment by waheedahmed** [comment]
Closing, it was only for discovery purpose.

**Pull request closed without merging**
