### PR TITLE
Removed SiteConfiguration._allowed_segment_events

### PR DESCRIPTION
**Pull request by clintonb**
Crisis resolved. This field is no longer needed.

LEARNER-2076

### CODE REVIEW

**Comment by clintonb** [comment]
FYI @edx/learner @edx/devops this the cleanup from this week's CPU crisis.

**Comment by feanil** [comment]
Will removing the column break the existing running app?

**Comment by clintonb** [comment]
@feanil thanks for asking! Usage of the field was removed by the first commit of https://github.com/edx/ecommerce/pull/1420.

**Review by feanil — APPROVED** [review]
We should make a note on the (Hawthorne)[https://openedx.atlassian.net/wiki/display/COMM/Hawthorn) page.  If other people in the community are using this it will break them while they are deploying.

@nedbat FYI

**Comment by clintonb** [comment]
@feanil this field was created yesterday for debugging purposes with help text stating the field was temporary. The likelihood of someone coming to rely on this field is quite low.

**Comment by feanil** [comment]
Gotcha. Thanks!

**Pull request merged**
