### PR TITLE
Ahsan/learner 1306 upgrade simple history

### PR DESCRIPTION
**Pull request by ahsan-ul-haq**

### CODE REVIEW

**Review by schenedx — APPROVED** [review]
👍

**Comment by schenedx** [comment]
We need https://openedx.atlassian.net/browse/DEVOPS-6521 ran before this can be properly deployed to production

**Review by clintonb — APPROVED** [review]
Do not merge until the history cleanup script has been run. Thinking long term, that script should probably be a management command that deletes all historical lines prior to a date specified on the command line.

**Comment by Ayub-Khan** [comment]
taking over this pull request will rebase and merge when Devops confirm they have ran the management command on prod.

**Comment by ahsan-ul-haq** [comment]
Created new PR https://github.com/edx/ecommerce/pull/1555 for this work closing this one.

**Pull request closed without merging**
