### PR TITLE
updated DRF and removed swagger

### PR DESCRIPTION
**Pull request by ahsan-ul-haq**
LEARNER-1306

### CODE REVIEW

**Review by schenedx — APPROVED** [review]
LGTM 👍 
Remember to squash your commits

**Review by clintonb — COMMENTED** [review]
So far, so good. Ping me again when your commits are squashed and tests are passing.

**Comment by ahsan-ul-haq** [comment]
@clintonb the work involving of updating basketview to have serializer_class is increasing the scope of this story so I have added a new story https://openedx.atlassian.net/browse/LEARNER-2643 for that.

**Comment by waheedahmed** [comment]
closing in favor of https://github.com/edx/ecommerce/pull/1492.

**Pull request closed without merging**
