### PR TITLE
Remove devserve

### PR DESCRIPTION
**Pull request by vkaracic**
Removing the command and documentation for `make devserve` added here: https://github.com/edx/ecommerce/commit/d8e258948cb6e8dc55e740efd2d27261edfc042c
Ecommerce on devstack uses the devstack settings by default now: https://github.com/edx/configuration/pull/2562

@adampalay @clintonb

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=531&repo=edx%2Fecommerce

**Comment by clintonb** [comment]
:+1:

**Comment by adampalay** [comment]
:-1: 
When I run `make serve` on devstack, it runs with production settings:
screenshot 2016-02-04 10 16 21

Maybe there's a bug with configuration? Or maybe I installed my devstack before your config change?

**Comment by vkaracic** [comment]
I believe it's the latter. This is what I get:
screenshot from 2016-02-04 16-20-47

**Comment by adampalay** [comment]
Ok, can we leave this in for backwards compatibility's sake (for example, I don't want to rebuild my devstack just for this?) You can add a note to `make devserve` that it's only in for backwards compatibility purposes.

**Comment by vkaracic** [comment]
Fine by me :)
@clintonb ?

**Comment by clintonb** [comment]
I'd rather not leave unnecessary code in the code base. @adampalay you don't need to rebuild devstack. Modify /edx/app/ecommerce/ecommerce_env to set `DJANGO_SETTINGS_MODULE` to `ecommerce.settings.devstack`.

**Comment by adampalay** [comment]
@clintonb , cool, but we should add that to documentation

**Pull request merged**
