### PR TITLE
Reverted hot fix for LEARNER-5603

### PR DESCRIPTION
**Pull request by Ayub-Khan**
Reverted hot fix for LEARNER-5603
As we fixed the root cause in https://github.com/edx/ecommerce/pull/1862
We do not need this code any more. 

This is a revert of https://github.com/edx/ecommerce/pull/1843

### CODE REVIEW

**Review by tasawernawaz — APPROVED** [review]

**Review by ahsan-ul-haq — APPROVED** [review]

**Review by robrap — APPROVED** [review]
Seems ok.  Please test on Stage that you can't recreate the issue once this is reverted.  Also, remember to remove the waffle flag from all environments once this is out there.
@waheedahmed can merge for you when it is ready.
Thanks.

**Comment by Ayub-Khan** [comment]
@robrap this can not be tested on stage as the root cause was fixed so voucher will be removed from the basket view if its already expired.

**Comment by robrap** [comment]
I think that is what I meant. Ensuring that the root cause fix still works as it did, to ensure that the original hot fix is no longer relevant. But, maybe you are saying something else.

**Comment by Ayub-Khan** [comment]
got it.

**Comment by waheedahmed** [comment]
@Ayub-Khan I'm assuming all comments are addressed here.

**Pull request merged**
