### PR TITLE
Moved create_from_breadcrumbs from migrations to management command

### PR DESCRIPTION
**Pull request by iamsobanjaved**
**Don't review: WIP**
https://openedx.atlassian.net/browse/BOM-1956

We need to do this change before Django-oscar2.1 [Release notes.](https://django-oscar.readthedocs.io/en/stable/releases/v2.1.html#what-s-new-in-oscar-2-1) it will reduce the complexity of the future upgrade PR and its just due to the 1 new field.

- catalogue.Category now has an **is_public** boolean field and its causing issues due to our custom migrations because is_public field appears in 51 migration

[create_from_breadcrumbs](https://github.com/django-oscar/django-oscar/blob/f2bb0fb73c83cb879fb2dec9184059dd96d814e0/src/oscar/apps/catalogue/categories.py#L38) using from custom data migrations giving error. The reason for this is explained in [Django's documentation](https://docs.djangoproject.com/en/3.0/topics/migrations/#data-migrations) on migrations - that the version of the model used in external code may be different from the one that this migration expects - which is why it fails.

`create_from_breadcrumbs` loading model like this and it expects is_public field in db.
```
from oscar.core.loading import get_model
Category = get_model('catalogue', 'category')
```
But in custom migrations it is loading older version of category model. I think its safe to move these commands from migration to management command. As these migrations already executed on master branch so its safe.

Issue on [stackover flow](https://stackoverflow.com/questions/63081636/django-oscar2-1-giving-errors-on-is-public-field-its-a-model-loading-issue) with detailed answer from django-oscar core contributor.

[Issue](https://github.com/django-oscar/django-oscar/issues/3465) reported on oscar.

### CODE REVIEW

**Comment by awais786** [comment]
We made 1 PR for upgrade and its failing https://github.com/edx/ecommerce/pull/3035 due to **is_public** field. That's why we decided to move those data migrations in this PR.

**Comment by awais786** [comment]
@robrap what do you think about this approach ?

**Comment by robrap** [comment]
@awais786: I'm not sure what the right plan would be.  Anyone setting up a fresh Open edX instance in Koa (the next release) would no longer get this migration and would need instructions for running the management command, which doesn't seem ideal.

There is no way to adjust the migration to make it work?  Generally speaking, removing migrations is not great.
I'm not sure if the following is a good idea, but is there a way to temporarily remove the migration now, and bring it back after Oscar 2.1, but before Koa?  I'll check in with others on their thoughts about this.

**Comment by feanil** [comment]
In general I agree with @robrap that moving the migrations to a management command is not great.  If we had used that approach from the beginning that would have been nice but given where we are, I think it would be be better to figure out a different way.  Is it possible to update the migrations to have a dependency on on the new is_public migration in oscar?  Or to check the version of oscar and do different things in the migrations based on the version that we're running?  

None of these answers are great and honestly this code is very edx.org specific so extracting to a management command would be nice but in this case, we'd need to update the docs as well and ensure the command is run regularly in production for when we add new categories.  Is the command idempotent so that this would be safe?

**Comment by dianekaplan** [comment]
@iamsobanjaved, @awais786, @robrap, @feanil: greetings! In our work toward upgrading django-oscar to 2.1, we've discussed a couple different approaches to resolving the previous awkwardness of using migrations to populate records in the data (starting with 0015_default_categories.py)- none of them are great, but we think this approach is comparatively the cleanest and would resolve this issue once and for all going forward. We're going to take a similar approach, making sure that the management command checks for the categories' existence before creating them (so it'll be idempotent), and making sure to update documentation that (a) new categories are added into this management command and (b) that a fresh Open edX install using ecommerce will run this as well.

**Comment by robrap** [comment]
Thanks @dianekaplan. I don't want to be a blocker. Here are some thoughts:
1. Include an ADR that explains what needs to be solved, what you decided, and its consequences.
2. In all the migrations you are emptying out, I'd add a brief comment that mostly points to the ADR for details, maybe with some hint about what used to live there.
3. Does it make sense to update one of the migrations to call the command, as [described in this article](https://avilpage.com/2019/09/django-tips-data-migrations.html)? It feels like that is a safe and reversible decision, given that you could always clear out that migration in the future. With new categories, you could always add a new migration and clear out the old one, as long as each named release will have at least one migration that calls the command.

Note: it may be getting into dangerous territory to combine migrations and calls to commands that could change over time, but not sure. :)

**Comment by dianekaplan** [comment]
> Thanks @dianekaplan. I don't want to be a blocker. Here are some thoughts:
> 
> 1. Include an ADR that explains what needs to be solved, what you decided, and its consequences.
> 2. In all the migrations you are emptying out, I'd add a brief comment that mostly points to the ADR for details, maybe with some hint about what used to live there.
> 3. Does it make sense to update one of the migrations to call the command, as [described in this article](https://avilpage.com/2019/09/django-tips-data-migrations.html)? It feels like that is a safe and reversible decision, given that you could always clear out that migration in the future. With new categories, you could always add a new migration and clear out the old one, as long as each named release will have at least one migration that calls the command.
> 
> Note: it may be getting into dangerous territory to combine migrations and calls to commands that could change over time, but not sure. :)

thanks, @robrap- 1 & 2 sound like a great idea- I'll do that! 
For #3- (we chatted over slack, but just recapping here for posterity)- the crux of the problem is importing and calling that 'create_from_breadcrumbs' oscar function before the migrations are finished, where we need to import the catalogue Category model. When there's been an update to an oscar model and we import it before the corresponding schema-changing migration is done, we have a mismatch between the live model and our database, which makes that 'Unknown column in field list' error. So for example, when the old category-creating '0015_default_categories.py' migration is run, it imports that oscar category model, whose newest version has the new is_public field, but that field isn't present in our database yet in that moment (it won't be added until the '0053_auto_20210922_1857.py' migration runs). See [here](https://github.com/edx/ecommerce/pull/3542/commits/2255139e7991af77c9d9933aa8a55102af3395b2) for specific migrations. 

Regarding the article's "Link Data Migrations & Schema Migrations" section, the migrations already do make use of RunPython- the trick is that we're adding the records with the help of a (changed) oscar class, rather than our local ORM. Regarding the article's "Watch Out For DB Queries" section, we could update each of the past category-adding migrations to only include specific fields, but it strikes me as a manual/confusing workaround that doesn't give us much value: we don't really care what date different categories were added, so it seems cleaner to remove all of this cruft and disarm this problem for good by adding categories more simply. (The PR I'm working on saves a text file with the categories we want, and the management command and test make sure they're there).  

The trick will be to make sure the management command gets run, with the help of the ADR and any other documentation. I'll also take a little time to look around and see if Django has an official/better way to populate default data.

**Comment by dianekaplan** [comment]
@iamsobanjaved, @awais786, @robrap, @feanil Just wanted to update for posterity: in the end we went with a different solution from Soban: implementing create_from_breadcrumbs locally, and using 'apps.get_model' to use the historical version of Django app registry (to get the old/current category model instead of the new one), and updating the old migrations to use that instead. Just wanted to close the loop so people don't wonder if we ever did that management command and have to remember to run it; we didn't and we don't :)

We did this instead: https://github.com/edx/ecommerce/pull/3552

**Pull request closed without merging**
