### PR TITLE
WL-484: Checkout buttons alignment fixed.

### PR DESCRIPTION
**Pull request by malikshahzad228**
@saleem-latif @mattdrayer 

New PR against https://github.com/edx/edx-themes/pull/32

### CODE REVIEW

**Comment by mattdrayer** [comment]
Code looks good -- with UI changes we need to include a screenshot for the PR review

**Comment by malikshahzad228** [comment]
@mattdrayer Screenshots are available on https://github.com/edx/edx-themes/pull/32

**Comment by mattdrayer** [comment]
AH, yes of course :)  okay, then we are good to go!  Looks like we need a rebase and then you are clear to merge -- 👍

**Comment by mattdrayer** [comment]
Please be sure to squash commits before merging

**Comment by saleem-latif** [comment]
👍

**Pull request merged**
