### PR TITLE
Added support for API documentation via Swagger

### PR DESCRIPTION
**Pull request by clintonb**

### CODE REVIEW

**Comment by clintonb** [comment]
@peter-fogg @adampalay please review

**Comment by adampalay** [comment]
@clintonb , when I run this locally, I'm getting a bunch of 429s

screenshot 2016-01-29 09 22 51

**Comment by clintonb** [comment]
Yep. We need to update throttling. For now, you can disable it by
commenting out that section in the DRF settings in base.py.

**Comment by adampalay** [comment]
@clintonb , sorry, I don't understand if there's a blocker or not. Other than that, it looks good!

**Comment by clintonb** [comment]
No blockers. I am opting not to increase throttling for the moment. Unless you are continually refreshing the docs, there should not be an issue with throttling.

**Comment by peter-fogg** [comment]
:+1: Nice. Perhaps even swag.

**Pull request merged**
