### PR TITLE
Disable SSI test

### PR DESCRIPTION
**Pull request by coryleeio**

### CODE REVIEW

**Comment by robrap** [comment]
Does the test ensure it is never mistakenly enabled? Or is that not a possibility?

**Comment by BenjiLee** [comment]
@coryleeio Could you add more context in the PR?

**Review by robrap — APPROVED** [review]
@coryleeio explained offline why this test is causing us issues.  All set.

**Comment by robrap** [comment]
@coryleeio: We do need this to be green before merging.

**Comment by coryleeio** [comment]
https://openedx.atlassian.net/browse/OPS-3301

has more context if needed for anyone later

**Review by BenjiLee — APPROVED** [review]

**Pull request merged**
