### PR TITLE
SE-3724: squash warnings

### PR DESCRIPTION
**Pull request by eLRuLL**
This PR squashes warnings as part of the [Squash a Warning event](https://discuss.openedx.org/t/squash-a-warning-earn-a-badge/3497), related to:

- Usage of the [edx_django_utils](https://github.com/edx/edx-django-utils) package
- Naive datetimes
- Warnings from old libsass version (it was from 2015)
- Usage of `RequestCustomAttributesMiddleware` instead `RequestMetricsMiddleware`

Reduced warnings when running tests from 5360 to 3076

**Note**
- This PR upgrades `libsass` and `cybersource-rest-client-python`, pinning `urllib3==1.25.11`
- The rest of the warnings should be improved once we do a django3 upgrade

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @eLRuLL! I've created [OSPR-5303](https://openedx.atlassian.net/browse/OSPR-5303) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by eLRuLL** [comment]
@edx-webhook this is ready for review

**Comment by natabene** [comment]
@eLRuLL Thank you for your contribution!

**Comment by eLRuLL** [comment]
this is ready for review btw :+1:

**Comment by eLRuLL** [comment]
just a reminder for a review here please

**Comment by nedbat** [comment]
@eLRuLL I was just discussing this with the owning squad this afternoon.  I suspect we will take some of these warning squashes and not others.  The e-commerce team here is overloaded and risk-averse.  Can we keep just some of these?

Thanks.

**Comment by eLRuLL** [comment]
@nedbat makes total sense, should I maybe separate these changes into multiple, more understandable PRs?

**Comment by nedbat** [comment]
Looking at the categories of changes, I think these will be OK:
- Usage of the edx_django_utils package
- Usage of RequestCustomAttributesMiddleware instead RequestMetricsMiddleware

These seem harder to review and be certain of:
- Naive datetimes
- Warnings from old libsass version (it was from 2015)

We are especially conservative with changes to ecommerce.  I hope it is OK to get half the warning-squashes!  If you could update this pull request to have the first two, I will work to get it merged.

Thanks so much for attacking the warnings, and especially for your patience and understanding.  I know we are not always the best collaborators... :)

**Comment by natabene** [comment]
@eLRuLL Will you have a chance to implement feedback that @nedbat provided?

**Comment by eLRuLL** [comment]
@natabene yes, I want to but still haven't found the time to work on this, is it too much trouble to leave this open? I can close it and create new PRs later if you want

**Comment by eLRuLL** [comment]
@natabene actually, it makes more sense to close this one as the changes require separate PRs already, so closing this one :+1:

**Comment by openedx-webhooks** [comment]
@eLRuLL Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/ecommerce&entry.867055334=https://github.com/edx/ecommerce/pull/3287&entry.1484655318=https://github.com/eLRuLL&entry.752974735=2020-12-14+05:22&entry.1917517419=2021-03-14+14:06&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
