### PR TITLE
Upgrade to Django REST Framework 3.2.3

### PR DESCRIPTION
**Pull request by clintonb**
- Upgraded DRF
- Upgraded DRF-JWT
- Upgraded DRF-Extensions

ECOM-2324

### CODE REVIEW

**Comment by clintonb** [comment]
@jimabramson @rlucioni @peter-fogg @bderusha

**Comment by peter-fogg** [comment]
:+1:

**Comment by jimabramson** [comment]
:+1:

**Comment by rlucioni** [comment]
:+1:

**Comment by bderusha** [comment]
:+1:

**Comment by rock345** [comment]
:+1:

**Pull request merged**
