### PR TITLE
Fix default Upgrade Deadline for courses

### PR DESCRIPTION
**Pull request by awaisdar001**
ECOM-3657

### CODE REVIEW

**Comment by awaisdar001** [comment]
@marcotuts This is the PR. 
FYI: @bderusha

**Comment by clintonb** [comment]
@bderusha please confirm that there is an issue, and this resolves it. I was under the impression this was deadline is reinforced in LMS.

**Comment by marcotuts** [comment]
Thanks for the note here @awaisdar001. Ultimately someone on the dev team will need to review, possibly @bderusha  (as noted by Clinton earlier.)

**Comment by awaisdar001** [comment]
@bderusha  Ping.

**Comment by bderusha** [comment]
@awaisdar001 Unfortunately this ticket and subsequent work is unnecessary.

The default dates are handled by the LMS and calculated based on the course end date.
This code would cause issues because the first time a course is saved we would set the date to the default in LMS, but then if the course end date changes, altering the upgrade deadline e-commerce and lms would be out of sync.

Secondly, I believe that this is a data bug, not a system bug.  All courses created after the default date code released work correctly.  All courses with deadlines set in ecommerce work correctly.  The gap is courses created before the default code launched which did not set a deadline in ecommerce.  Those now look like they should be getting a default date. but they aren't.

I will run some queries and attach the impacted courses to the ticket.

I think we can close this PR.  Sorry for not catching this earlier before you started work.

**Comment by awaisdar001** [comment]
Closing  :(

**Pull request closed without merging**
