### PR TITLE
Replace rest_framework_swagger with drf_yasg

### PR DESCRIPTION
**Pull request by NeOneSoft**
This PR was created following https://github.com/edx/upgrades/issues/17 to switch django rest swagger to drf-yasg

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @NeOneSoft! I've created [OSPR-6126](https://openedx.atlassian.net/browse/OSPR-6126) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@NeOneSoft Thanks so much for your contribution. Please let me know once this is ready.

**Comment by natabene** [comment]
@NeOneSoft Just checking if you are still interested in pursuing this, let me know.

**Comment by NeOneSoft** [comment]
@natabene Sorry about my delay to answer, I have been a little bit busy to finish some repos related with this issues. Could you please help me to find someone to continue this effort?

**Comment by openedx-webhooks** [comment]
@NeOneSoft Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/ecommerce&entry.867055334=https://github.com/openedx/ecommerce/pull/3539&entry.1484655318=https://github.com/NeOneSoft&entry.752974735=2021-10-11+21:07&entry.1917517419=2022-02-21+12:33&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
