### PR TITLE
WIP: Upgrade django-oscar to 2.1

### PR DESCRIPTION
**Pull request by iamsobanjaved**
Fixed imports in customer/utils
Set surcharge to none

### CODE REVIEW

**Comment by iamsobanjaved** [comment]
@feanil @robrap I have temporarily sorted migrations to resolve issues for django-oscar upgrade. Now i am having an issue which is the limitation of mysql and django-oscar is not going to fix this as they say, they provide support for Postgres. This is a major blocker in this upgrade process.

https://github.com/django-oscar/django-oscar/issues/3335#issuecomment-611862398

**Comment by feanil** [comment]
@iamsobanjaved when does that error occur? At start-up? As part of some specific transaction? Something else?

**Comment by iamsobanjaved** [comment]
@feanil  we are still investigating this issue.

Here is the traceback

>query = b"UPDATE `catalogue_category` SET `ancestors_are_public` = NOT EXISTS(SELECT U0.`id` FROM `catalogue_category` U0 WHER...E(REPLACE(REPLACE(U0.`path`, '\\\\', '\\\\\\\\'), '%', '\\%'), '_', '\\_'), '%'))) WHERE `catalogue_category`.`id` = 3"
    def query(self, query):
        # Since _mysql releases GIL while querying, we need immutable buffer.
        if isinstance(query, bytearray):
            query = bytes(query)
>       _mysql.connection.query(self, query)
E       MySQLdb._exceptions.OperationalError: (1093, "You can't specify target table 'catalogue_category' for update in FROM clause")

**Comment by iamsobanjaved** [comment]
Category management is broken in django-oscar 2.1 if used with mysql db

https://github.com/django-oscar/django-oscar/issues/3451

**Comment by feanil** [comment]
Is this a feature we actually use or just one that's currently enabled?

**Comment by iamsobanjaved** [comment]
No we are not using this, its a new feature introduced in the latest version.

**Comment by feanil** [comment]
Then can we just turn the feature off?

**Comment by e0d** [comment]
It looks like we can likely just turn this off: https://github.com/django-oscar/django-oscar/issues/3335

**Pull request closed without merging**
