### PR TITLE
Log the repr() of response content when CreditCourse publication fails

### PR DESCRIPTION
**Pull request by rlucioni**
@edx/ecommerce

### CODE REVIEW

**Comment by clintonb** [comment]
Please add a comment to the commit message and/or code explaining this change.

**Comment by clintonb** [comment]
:+1:

**Comment by jimabramson** [comment]
nitpick: square brackets are not going to be needed to demarcate the value of the body.

otherwise :+1:    thanks for squeezing this in

**Comment by rlucioni** [comment]
@clintonb @jimabramson I've made both suggested changes. Thanks for the feedback.

**Comment by jimabramson** [comment]
:+1:

**Pull request merged**
