### PR TITLE
[WIP]Use config instead of hard code currency 

### PR DESCRIPTION
**Pull request by WeJie**
Remove hard code currency-code and currency-symbol and use config instead.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @WeJie! I've created [OSPR-2826](https://openedx.atlassian.net/browse/OSPR-2826) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@WeJie Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by natabene** [comment]
@WeJie  Thank you for signing the agreement. Please let us know when this PR is ready to be looked at.

**Comment by natabene** [comment]
@WeJie I am curious, are you still interested in pursuing this?

**Comment by WeJie** [comment]
@natabene I don't think I will have time to finish it recently, so I shall close this PR for now.

**Comment by openedx-webhooks** [comment]
@WeJie Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/ecommerce&entry.867055334=https://github.com/edx/ecommerce/pull/1989&entry.1484655318=https://github.com/WeJie&entry.752974735=2018-11-24+07:04&entry.1917517419=2019-04-10+01:36&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
