### PR TITLE
ziafazal/WL-632: fixed horizontal scrolling on basked page when viewed in mobile device

### PR DESCRIPTION
**Pull request by ziafazal**
This PR has change to fix horizontal scrolling on basked page when viewed in mobile device.
[WL-632](https://openedx.atlassian.net/browse/WL-632) has more details on the issue.
@douglashall could you please review?

### CODE REVIEW

**Comment by douglashall** [comment]
@ziafazal This does not seem to solve the issue. What if we just remove the `btn` and `btn-link` classes from the basket switch `<a>` in the template? Note we will also have to do this for each theme in the edx-themes repo.

**Comment by ziafazal** [comment]
@douglashall removing `btn` and `btn-link` classes would remove the styling and that would give us unexpected UI. This issue is not related to any of the WL sites theming it is a valid issue for edx.org too so ideally we should fix it inside the ecommerce app as this PR does.

**Comment by douglashall** [comment]
@ziafazal Removing the `btn` and `btn-link` classes did not seem to affect styling for me. Does the change you have here fix the issue for you? It did not seem to fix it for me.

**Comment by douglashall** [comment]
@ziafazal Now that I think about it though, this will no longer be an issue when we move to the new single page checkout that another team is working on. Please close out this PR and I'll close the Jira issue.

**Comment by ziafazal** [comment]
Changes no longer needed since we a new checkout page.

**Pull request closed without merging**
