### PR TITLE
Revert "SOL-1926: Add org filter on courses"

### PR DESCRIPTION
**Pull request by mattdrayer**
Reverts edx/ecommerce#874

@rlucioni

### CODE REVIEW

**Comment by mattdrayer** [comment]
@malikshahzad228 FYI

**Comment by rlucioni** [comment]
👍

**Comment by mattdrayer** [comment]
Will merge after checks clear

**Comment by mattdrayer** [comment]
CI has passed, coverage appears to be stuck -- going ahead with the merge.

**Comment by mattdrayer** [comment]
Oh, I can't do that...I have to wait...

**Pull request merged**
