### PR TITLE
Text improvement on credit checkout page

### PR DESCRIPTION
**Pull request by zubair-arbi**
ECOM-2339

@awais786 @ahsan-ul-haq @aamir-khan @tasawernawaz 
Update credit instructions for link `How does credit work?` on credit checkout page.
screen shot 2015-10-01 at 12 52 10 pm

### CODE REVIEW

**Comment by tasawernawaz** [comment]
lgtm :+1:

**Comment by zubair-arbi** [comment]
@srpearce Please reveiw.
Since the content for `How does credit work?` on credit checkout page is add by a separate js view which has no access to course name and also for now the credit hours are attached to a course instead of its credit providers that why I omitted both `course_name` and `credit hours` from the text update.

**Comment by srpearce** [comment]
Is it possible to make **Checkout** and **Checkout with PayPal** bold?

Also, the "A new model for the American Research University..." text is new and could use a copy edit—can you tell me where it came from?

**Comment by zubair-arbi** [comment]
1. Yes (I will update the PR)
2. This is a dummy text which I added on my local machine for `ASU` credit provider.

**Comment by srpearce** [comment]
OK, cool. :+1: then.

**Comment by clintonb** [comment]
:+1:

**Pull request merged**
