### PR TITLE
Fill in required invoice fields for coupon acceptance tests.

### PR DESCRIPTION
**Pull request by mjfrey**
Need to add new required invoice fields to coupon creation for acceptance tests.

### CODE REVIEW

**Comment by mjfrey** [comment]
@vkaracic

**Comment by vkaracic** [comment]
The reason why this needs to be done is because invoice fields are made required. If these fields are not needed, you can just select `N/A` as the invoice type without needing to fill out any additional invoice field.
If you want to leave it like this, I suggest filling out the `price` field as well which would cover all required fields.

**Comment by mjfrey** [comment]
@vkaracic added price.

**Comment by vkaracic** [comment]
:+1:

**Pull request merged**
