### PR TITLE
[BB-4552] feat: Add support for fixed rate in ecommerce

### PR DESCRIPTION
**Pull request by alfredchavez**
## Description

Ecommerce does not support tax rates for its payments(DefaultStrategy uses a NoTax strategy), this PR adds support for a fixed tax rate through a new django setting `TAX_RATE` that is applied to all products.
Also the default value for the `TAX_RATE` setting is 0.0, preserving the previous platform behaviour.

## Supporting information

Jira Issue: [BB-4552](https://tasks.opencraft.com/browse/BB-4552)

## Testing instructions

- Check that the added tests make sense and run without failure

- Change the `TAX_RATE` to a decimal value(like "0.3")
- Try to make a purchase(could be the certificate upgrade of the demo course)
- Verify that the total value displayed on basket and invoice includes the tax rate

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @alfredchavez! I've created [OSPR-5961](https://openedx.atlassian.net/browse/OSPR-5961) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by giovannicimolin** [comment]
@natabene @nedbat It looks like the CI checks weren't triggered for this (@alfredchavez is a member of OpenCraft, and this was created from our fork). Can you check or trigger a CI run for this?

**Comment by giovannicimolin** [comment]
~~jenkins run all~~ 

Didn't work, but it was worth a shot...

**Comment by natabene** [comment]
@alfredchavez Thank you for your contribution. @giovannicimolin I will kick them off now.

**Comment by giovannicimolin** [comment]
@alfredchavez Quality checks are failing, can you fix them (plus any other CI issues) and ping me for another review round Monday?

**Comment by alfredchavez** [comment]
Hi @giovannicimolin I have fixed the "import order" issues, but CI checks are not running until approval

**Comment by giovannicimolin** [comment]
@natabene Can you kick off the CI checks here again? Is there something we can do to unblock these checks from OpenCraft repos?

**Comment by giovannicimolin** [comment]
@alfredchavez Can you double-check that all tests are passing locally?

**Comment by giovannicimolin** [comment]
@natabene Can you trigger a CI run for this again?

**Comment by natabene** [comment]
Ok, I think they are running now.

**Comment by mphilbrick211** [comment]
@giovannicimolin is this still in progress? Or, can it be closed?

**Comment by mphilbrick211** [comment]
> @giovannicimolin is this still in progress? Or, can it be closed?

Friendly ping on this @giovannicimolin :)

**Comment by giovannicimolin** [comment]
@mphilbrick211 Sorry for missing the pings.

We will not be pursuing this any longer, but I don't have permission to close the PR. Can you close it for me?

**Comment by mphilbrick211** [comment]
Closing, per Giovanni.

**Comment by openedx-webhooks** [comment]
@alfredchavez Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/ecommerce&entry.867055334=https://github.com/openedx/ecommerce/pull/3484&entry.1484655318=https://github.com/alfredchavez&entry.752974735=2021-08-11+16:13&entry.1917517419=2022-12-07+22:01&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
