### PR TITLE
Update installed extensions version

### PR DESCRIPTION
**Pull request by rlucioni**
@feanil and @clintonb, part 2 of 2.

### CODE REVIEW

**Comment by clintonb** [comment]
:+1:

**Comment by clintonb** [comment]
@rlucioni Also update `requirements/not_editable.txt`.

**Comment by feanil** [comment]
:+1:

**Comment by feanil** [comment]
:+1:

**Comment by rlucioni** [comment]
@clintonb `requirements/not_editable.txt` is the only file changed in this PR.

**Comment by clintonb** [comment]
:facepunch: Oops.

**Pull request merged**
