### PR TITLE
Allow multiple sites for single partner.

### PR DESCRIPTION
**Pull request by waheedahmed**
Allow multiple site configuration objects against same partner for different sites.

LEARNER-5052

### CODE REVIEW

**Review by feanil — COMMENTED** [review]
@waheedahmed can you provide the output of the `sqlmigrate` management command so I can examine the SQl that this is going to try to run?  On the surface this looks like the right change.

**Comment by waheedahmed** [comment]
@feanil here is the `sqlmigrate` output:
```
root@27dcc37d360d:/edx/app/ecommerce/ecommerce# ./manage.py sqlmigrate core 0045
BEGIN;
--
-- Alter field partner on siteconfiguration
--
ALTER TABLE `core_siteconfiguration` DROP INDEX `core_siteconfiguration_partner_id_75739217_uniq`;
CREATE INDEX `core_siteconfiguration_partner_id_75739217` ON `core_siteconfiguration` (`partner_id`);
COMMIT;
```

**Comment by waheedahmed** [comment]
I will update this PR after merging https://github.com/edx/ecommerce/pull/1757 so that management commands can use `default_site`.

**Comment by waheedahmed** [comment]
@staubina, @edx/learner-spartans Please review.

**Review by raeeschachar — APPROVED** [review]
Looks good

**Review by staubina — APPROVED** [review]

**Comment by staubina** [comment]
@feanil Are you comfortable with the SQL you are seeing above?

**Pull request merged**
