### PR TITLE
bugfix: allow proper currency rendering in case of discount coupons applied

### PR DESCRIPTION
**Pull request by pulkitpahwa**
The currency is currently hard-coded for the discount applied part on checkout page. This PR attempts to resolve it

1. My default currency is Rs. (Indian National Rupee). In case of
coupons, the discount applied was being rendered in dollars.

2. The discount currency should be the same as the default currency, and
hence the code change

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pulkitpahwa! I've created [OSPR-2484](https://openedx.atlassian.net/browse/OSPR-2484) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/ecommerce/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by mduboseedx** [comment]
@pulkitpahwa Thank you for the contribution! When you have a moment, could you please sign and send in the Contribution agreement mentioned in the early comment? This only needs to be done once and we can then review all of your code changes going forward.

**Comment by natabene** [comment]
@pulkitpahwa Hi, we have not heard from your for a while. I am closing this PR, but feel free to open a new one if you still want to pursue this.

**Comment by openedx-webhooks** [comment]
@pulkitpahwa Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/ecommerce&entry.867055334=https://github.com/edx/ecommerce/pull/1825&entry.1484655318=https://github.com/pulkitpahwa&entry.752974735=2018-06-25+14:48&entry.1917517419=2018-10-11+18:53&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
