### PR TITLE
feat: Replace django-threadlocals with django-crum

### PR DESCRIPTION
**Pull request by giovannicimolin**
## Description

Contribution as Core Comitter.

Remove usages of `threadlocals` with `django-crum` to unblock Django 3.2 upgrade: https://github.com/edx/upgrades/issues/36.

## Supporting information

- [Django 3.2 upgrades](https://github.com/orgs/edx/projects/5)
- https://github.com/edx/upgrades/issues/36

## Testing instructions

1.  Check that tests are passing.
2.  Test a payment flow.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @giovannicimolin! I've created [OSPR-6231](https://openedx.atlassian.net/browse/OSPR-6231) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by giovannicimolin** [comment]
I don't expect this to pass the first test run.

**Comment by giovannicimolin** [comment]
@awais786 (CC @natabene) Here is the new PR that uses `django-crum`. Due to a particularity with its implementation, I've had to patch the library (see comments and commit message on 2ce33595a40631caab8a070b994233723313fc41). 
Here's the line that causes issues: https://github.com/ninemoreminutes/django-crum/blob/master/crum/__init__.py#L110.

The same issue happened with edx-platform a few years ago, and there's an patch in there as well (https://github.com/edx/edx-platform/blob/master/common/djangoapps/util/views.py#L84). I did not apply it here because I'd need to decorate every endpoint.

References:
- https://github.com/edx/edx-platform/pull/17446
- https://openedx.atlassian.net/browse/CRI-75

Please revisit my previous approach (https://github.com/edx/ecommerce/pull/3503) before reviewing and merging this. It removes a depencency from the platform and reduces the need for patches.

CC @edx/ccp-committer-bradenmacdonald

**Comment by natabene** [comment]
@giovannicimolin Thank you for your contribution. Please let me know once this is ready for our review.

**Comment by giovannicimolin** [comment]
@natabene Sure, I just need to fix the tests now!

**Comment by giovannicimolin** [comment]
@Jawayria @awais786 @natabene This is ready for review.

**Comment by awais786** [comment]
Right now repo is in code freeze. We will review later on.

**Comment by giovannicimolin** [comment]
@awais786 :+1: - I'll wait for your ping and review.

**Comment by mphilbrick211** [comment]
@giovannicimolin @awais786 - can this be closed as there has been no activity in a year?

**Comment by mphilbrick211** [comment]
> @giovannicimolin @awais786 - can this be closed as there has been no activity in a year?

Just following up on this @giovannicimolin :)

**Comment by giovannicimolin** [comment]
@mphilbrick211 Yup, this is good to close.

**Comment by openedx-webhooks** [comment]
@giovannicimolin Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/ecommerce&entry.867055334=https://github.com/openedx/ecommerce/pull/3580&entry.1484655318=https://github.com/giovannicimolin&entry.752974735=2021-11-18+22:37&entry.1917517419=2022-12-01+14:32&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
