### PR TITLE
MAYN-271: Enrollment code acceptance test.

### PR DESCRIPTION
**Pull request by malikshahzad228**
Add enrollment code acceptance tests [MAYN-271](https://openedx.atlassian.net/browse/MAYN-271).

### CODE REVIEW

**Comment by mattdrayer** [comment]
@malikshahzad228 -- this is a good first-round set of tests which will help to prevent regressions of the Otto bulk purchasing functionality -- please work with @kashifch to ensure that we have the most critical scenarios covered -- we can work on adding corner cases and less likely scenarios with a follow-on PR.

**Comment by mattdrayer** [comment]
👍 after @kashifch has confirmed the critical scenarios are covered

**Comment by aghaawais01** [comment]
@malikshahzad228 I think it would be good if you add a test for user entering less than 1 value in the Quantity field and trying to update.

**Comment by vkaracic** [comment]
Out of curiosity, are you running these tests locally and what command are you using to run them? (I'm interested in the env variables)

**Comment by malikshahzad228** [comment]
@vkaracic Command to run the tests for a single file is like

`ECOMMERCE_URL_ROOT="http://localhost:8002" LMS_URL_ROOT="http://localhost:8000" LMS_USERNAME="staff" LMS_EMAIL="staff@example.com" LMS_PASSWORD="edx" ACCESS_TOKEN="dd5659adca769c08e8a12338f1c0eba4c50b352e" LMS_HTTPS="True" LMS_AUTO_AUTH="False" PAYPAL_EMAIL="zia@edx.org" PAYPAL_PASSWORD="testing1234" HONOR_COURSE_ID="course-v1:Mainsite+MAIN101+01" VERIFIED_COURSE_ID="course-v1:MITProfessionalX+MIT001+2016_T1" BULK_PURCHASE_SKU=6D6419D ENABLE_CYBERSOURCE_TESTS='True' nosetests -v acceptance_tests/test_bulk_purchase.py`

OR to run all tests like:

`ECOMMERCE_URL_ROOT="http://localhost:8002" LMS_URL_ROOT="http://localhost:8000" LMS_USERNAME="staff" LMS_EMAIL="staff@example.com" LMS_PASSWORD="edx" ACCESS_TOKEN="dd5659adca769c08e8a12338f1c0eba4c50b352e" LMS_HTTPS="True" LMS_AUTO_AUTH="False" PAYPAL_EMAIL="zia@edx.org" PAYPAL_PASSWORD="testing1234" HONOR_COURSE_ID="course-v1:Mainsite+MAIN101+01" VERIFIED_COURSE_ID="course-v1:MITProfessionalX+MIT001+2016_T1" BULK_PURCHASE_SKU=6D6419D ENABLE_CYBERSOURCE_TESTS='True' make accept`

But you have to change the `course_ids`, and `BULK_PURCHASE_SKU` and other variables with your database records.

**Comment by mattdrayer** [comment]
Updating this PR and will merge after the final round of checks are passing -- we can always add more test coverage (please file tickets for any new tests we would like to create)

**Pull request merged**
