### PR TITLE
Added Stripe Payment Processor

### PR DESCRIPTION
**Pull request by clintonb**
This integration supports credit card payments, Apple Pay, and the Payment Request API using Stripe as the backend processor.

Related pull requests
* Payment processor document (#1539)
* Decoupling Apple Pay from CyberSource (#1540)

TODO
- [x] Add info about ngrok and SSL testing to Apple Pay section
- [x] Add diagram of Stripe token usage

### CODE REVIEW

**Comment by clintonb** [comment]
As with the CyberSource processor, the JS code won't be unit-tested. In this case, I am unable to mock the `Stripe` entity. The e2e tests for credit cards remain valid for Stripe as they are for CyberSource. However, given that edX does not use Stripe, we will not test this integration with any regularity.

**Comment by clintonb** [comment]
~~I have another branch that makes use of Stripe Elements to implement payment requests: https://github.com/edx/ecommerce/tree/stripe-payment-request. Finishing that work will require more research into understanding what data is available from the token. At present, I don't know how to get the billing address.~~

This branch now includes support for Apple Pay and the Payment Requests API.

**Comment by pomegranited** [comment]
@clintonb I am sorry to hear you're leaving edx!  Thank you for all your help and contributions over the years, and I wish you the best for the future.

Thanks for pinging me on this -- @renevatium can we pull this work into our current project?

**Comment by renevatium** [comment]
@pomegranited we certainly can. Thanks for the heads up! Will get the team to test it out.

**Comment by clintonb** [comment]
@pomegranited @renevatium note that I have updated the branch with support for Apple Pay and the Payment Requests API. When do you anticipate you'll be done with your testing? If that testing will take longer than a week, I may just merge this as-is and resolve any issues as they arise.

**Comment by pomegranited** [comment]
@clintonb I'll let @renevatium confirm, but I don't think we'll be able to test it this week.  So feel free to merge, and rely on us to submit fixes as needed.

Thanks for getting this change in!

**Comment by renevatium** [comment]
@clintonb great work on this, thank you! Have everything set up but the process dies at checkout to the NotImplementedError from the get_transaction_parameters function. If I get around that by returning an empty dict, I get a KeyError on parameters.pop('payment_page_url') in baskets.py. I feel like I'm missing a configuration element and/or misunderstanding how to engage the Stripe UI. Could you possibly point me in the right direction?

**Comment by clintonb** [comment]
@renevatium did you read the docs at https://edx-ecommerce.readthedocs.io/en/latest/additional_features/payment_processors.html? `Stripe. get_transaction_parameters` is intentionally not implemented because it should never be called. If you've followed the documentation, please post a stack trace of the error you see at checkout.

**Comment by renevatium** [comment]
@clintonb have gone through all the docs and have had e-commerce running in production since last year. I assumed as much, but looks like the issue is that client side processing is not working (the flag is enabled for everyone and have set Stripe as client processor). Hence the server side logic gets called. Will investigate today. Thanks for getting back to me, will let you know if I don't come right.

**Comment by renevatium** [comment]
@clintonb got it. Issues were out of date migrations and getting client configuration variable across microsites. Thanks for putting all this together. Appreciate the effort 👍

**Comment by clintonb** [comment]
@renevatium Im glad it all worked out. You’re welcome!

**Pull request merged**
