### PR TITLE
Switch to enterprise catalog behind waffle flag

### PR DESCRIPTION
**Pull request by bbaker6225**
Moves ecommerce's usage of the contains_content_items endpoint to
using the new enterprise catalog service behind a waffle flag. We will
use this flag to slowly cut over traffic to using the new service and
endpoint there.

ENT-2573

### CODE REVIEW

**Review by brittneyexline — APPROVED** [review]
code looks good! my only concern is that we may not have access to ecommerce django admin to change the waffle flag... iirc no one has access to ecommerce django admin anymore, but i'm not sure. do you happen to know?

**Comment by bbaker6225** [comment]
Correct, no one except devops has access to ecommerce admin, so I think we'd need to coordinate with them for the rollout/testing on this.
Unless we can temporarily get access to one part of ecommerce admin that is

**Comment by bbaker6225** [comment]
@brittneyexline Are you ok with this approach given that we don't have access to ecommerce django admin?

**Review by adamstankiewicz — APPROVED** [review]

**Comment by brittneyexline** [comment]
yes - i did not mean to block the pr, just point that out. we should be able to proceed though

**Pull request merged**
