### PR TITLE
Django Oscar Upgrade to version 3.2.2

### PR DESCRIPTION
**Pull request by zubair-ce07**
# ⛔️ MAIN BRANCH WARNING! 2U EMPLOYEES must make branches against the 2u/main BRANCH

- [ ] I have checked the branch to which I would like to merge.

# ⛔️ DEPRECATION WARNING

**This repository is deprecated and in maintainence-only operation while we work on a replacement, please see [this announcement](https://discuss.openedx.org/t/deprecation-removal-ecommerce-service-depr-22/6839) for more information.**

Although we have stopped integrating new contributions, we always appreciate security disclosures and patches sent to [security@edx.org](mailto:security@edx.org)

## Required Testing
- [ ] Before deploying this change, complete a purchase in the stage environment. 
(^ We can remove that manual check once REV-2624 is done and the corresponding e2e test runs again)

## Description

Describe what this pull request changes, and why these changes were made. How will these changes affect other people, installations of edx, etc.?
Please include links to any relevant ADRs, design artifacts, and decision documents. Make sure to document the rationale behind significant changes in the repo, per [OEP-19](https://open-edx-proposals.readthedocs.io/en/latest/oep-0019-bp-developer-documentation.html), and can be
linked here.

Useful information to include:
- Which edX user roles will this change impact? Common user roles are "Learner", "Course Author", "Developer", and "Operator".
- Include screenshots for changes to the UI (ideally, both "before" and "after" screenshots, if applicable).
- Provide links to the description of corresponding configuration changes. Remember to correctly annotate these changes.

## Supporting information

Link to other information about the change, such as Jira issues, GitHub issues, or Discourse discussions.
Be sure to check they are publicly readable, or if not, repeat the information here.

## Testing instructions

Please provide detailed step-by-step instructions for testing this change; how did YOU test this change?

## Other information

Include anything else that will help reviewers and consumers understand the change.
- Does this change depend on other changes elsewhere?
- Any special concerns or limitations? For example: deprecations, migrations, OpenEdx vs. edx.org differences, development vs. production environment differences, security, or accessibility.

### CODE REVIEW

**Comment by awais786** [comment]
```
 Applying basket.0016_alter_lineattribute_value... OK
```
This migration executed.

**Comment by awais786** [comment]
```
  File "/edx/app/ecommerce/venvs/ecommerce/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/edx/app/ecommerce/venvs/ecommerce/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/edx/app/ecommerce/venvs/ecommerce/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/edx/app/ecommerce/venvs/ecommerce/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/edx/app/ecommerce/venvs/ecommerce/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/edx/app/ecommerce/venvs/ecommerce/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'basket_line.tax_code' in 'field list'")
```

**Comment by awais786** [comment]
It seems like makemigrations command needs to run on this branch
````
Migrations for 'basket':
  ecommerce/extensions/basket/migrations/0017_line_tax_code.py
    - Add field tax_code to line
Migrations for 'offer':
  ecommerce/extensions/offer/migrations/0056_auto_20231211_1225.py
    - Add field upload_type to rangeproductfileupload
    - Alter field description on historicalrange
    - Alter field description on range
Migrations for 'order':
  ecommerce/extensions/order/migrations/0028_auto_20231211_1225.py
    - Change Meta options on surcharge
    - Add field tax_code to historicalline
    - Add field shipping_tax_code to historicalorder
    - Add field tax_code to line
    - Add field tax_code to lineprice
    - Add field shipping_tax_code to order
    - Add field tax_code to surcharge
 ```

**Comment by awais786** [comment]
After running makemigration and migrate following migration rans.
```  
Applying basket.0017_line_tax_code... OK
  Applying offer.0056_auto_20231211_1225... OK
  Applying order.0028_auto_20231211_1225... OK
```

**Review by christopappas — APPROVED** [review]
These have been QA'd locally and in a (production-like) sandbox environment, and have passed the team's review. 👍

**Pull request closed without merging**
