### PR TITLE
Removed unnecessary message on basket view

### PR DESCRIPTION
**Pull request by clintonb**
This message is confusing to buyers, and makes no sense given that you can never view the page if you have previously-purchased items in your basket.

LEARNER-1650

### CODE REVIEW

**Review by schenedx — APPROVED** [review]
👍

**Comment by schenedx** [comment]
@clintonb This definitely addresses the bug.
Can you help me understand why you say learner cannot view basket page if they have an already purchased item in their basket?

**Comment by clintonb** [comment]
@schenedx if the item has already been purchased, the learner will be show the error page. See https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/basket/views.py#L117-L119

**Comment by schenedx** [comment]
@clintonb I see. I just never seen the error message. Make sense.

**Pull request merged**
