### PR TITLE
Using Codecov for coverage reporting

### PR DESCRIPTION
**Pull request by clintonb**

### CODE REVIEW

**Comment by clintonb** [comment]
FYI @jimabramson @rlucioni

**Comment by rlucioni** [comment]
@clintonb some context for those less familiar with the motivations behind this change would be nice.

**Comment by clintonb** [comment]
We are trying out codecov in place of coveralls.

**Comment by rlucioni** [comment]
@clintonb do we want to continue using coveralls in the meantime for the other repos we own?

**Comment by clintonb** [comment]
Yes.

**Comment by jimabramson** [comment]
good call.

**Pull request merged**
