### PR TITLE
feat!: remove Transifex calls for FC-0012 - OEP-58

### PR DESCRIPTION
**Pull request by shadinaif**
Breaking change!
---

This change breaks the Jenkins transifex integration which has been deprecated in favor of the new GitHub Transifex App integration as part of [OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

Changes
---

- [x] Removes direct use of `tx pull` and `tx push` commands
- [x] Remove source and language translations from the repositories, hence no `.po` or `.mo` files will be committed into the repos.
- [x] Remove Transifex related `Makefile` targets and configuration files.
- [ ] ~~Use the OEP-58 JavaScript translations from the Open edX platform~~ does not apply
- [ ] Remove `transifex-client` from requirements

Merge timeline
---

This should only be merged after [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification) is fully implemented.

The timing announcement will be shared by @brian-smith-tcril on [#translations-project-fc-0012](https://openedx.slack.com/archives/C04R6TUJB7T) Open edX Slack channel.

**## Keep this pull request as a draft to prevent an accidental merge. ##**

Pre-merge checklist
---

- [ ] https://github.com/openedx/wg-translations/issues/20 is approved

References
---

This contribution is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

Up-to-date project overview and details are available in the [Approach Memo and Technical Discovery: Translations Infrastructure Implementation](https://docs.google.com/document/d/11dFBCnbdHiCEdZp3pZeHdeH8m7Glla-XbIin7cnIOzU/edit#) document.

Join the conversation on [Open edX Slack #translations-project-fc-0012](https://openedx.slack.com/archives/C04R6TUJB7T).

Check the links above for full information about the overall project.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @shadinaif! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @shadinaif - I don't think the revenue squad is reviewing this repo any longer. Might be best to check with Brian and Sabrina on getting this reviewed.

**Review by OmarIthawi — APPROVED** [review]
@brian-smith-tcril this one is ready for merge.

Thanks @shadinaif!

**Review by brian-smith-tcril — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@shadinaif 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/ecommerce&entry.867055334=https://github.com/openedx/ecommerce/pull/4116&entry.1484655318=https://github.com/shadinaif&entry.752974735=2024-02-06+06:25&entry.1917517419=2024-03-18+18:59&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
