### PR TITLE
[SOL-1864] Hide code field for quantity > 1 coupons

### PR DESCRIPTION
**Pull request by vkaracic**
Hide code field when quantity > 1, and hide quantity field when code is entered.

https://openedx.atlassian.net/browse/SOL-1864

Reviewers:
- [x] @marjev 
- [x] @mattdrayer

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=826

**Comment by mattdrayer** [comment]
Do we have a Jasmine test that covers this change?

**Comment by vkaracic** [comment]
I'll create a few.

**Comment by vkaracic** [comment]
I edited the existing ones in https://github.com/edx/ecommerce/pull/826/commits/4d0ff45b3da9f8aeac3ff9c7ad7d67a88e38ebc5. I think they should suffice.

**Comment by marjev** [comment]
Looks good. :+1:

**Comment by mattdrayer** [comment]
LGTM as well -- thanks for adding the tests -- 👍 for merge after Jenkins has approved

**Comment by vkaracic** [comment]
Jenkins has no power here muhahaha :smile:

**Pull request merged**
