### PR TITLE
Revert "WL-330: Multi-Site Branding in Otto"

### PR DESCRIPTION
**Pull request by mattdrayer**
Reverts edx/ecommerce#649

### CODE REVIEW

**Comment by mattdrayer** [comment]
@renzo @jibsheet, FYI

**Comment by jibsheet** [comment]
👍  Thanks for jumping on this until we can figure out what happened.

**Comment by mattdrayer** [comment]
@saleem-latif FYI

**Comment by mattdrayer** [comment]
I'll merge after the checks pass

**Comment by mattdrayer** [comment]
Error information:

20:19:37 stderr: CommandError: An error occurred during rendering /edx/app/ecommerce/ecommerce/ecommerce/templates/coupons/offer.html: 'css/base/main.css' could not be found in the COMPRESS_ROOT '/edx/var/ecommerce/staticfiles' or with staticfiles.

URL:
http://jenkins.edx.org:8080/job/ansible-provision-continuous-integration/26522/console

**Pull request merged**
