### PR TITLE
chore: upgrade requirements

### PR DESCRIPTION
**Pull request by xitij2000**
## Description
Update dependencies to remove rest-condition for Django 3.2 support

## Supporting information

https://github.com/edx/upgrades/issues/2

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @xitij2000! I've created [OSPR-6107](https://openedx.atlassian.net/browse/OSPR-6107) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@xitij2000 Thank you very much for this PR, is this ready for our review?

**Comment by xitij2000** [comment]
@natabene  Yes, it's good to review.

**Comment by mzulqarnain1** [comment]
We will review this PR when we get to ecommerce Django 3.2 upgrade.

**Comment by natabene** [comment]
@mzulqarnain1 Can this be reviewed?

**Comment by openedx-webhooks** [comment]
@xitij2000 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/ecommerce&entry.867055334=https://github.com/openedx/ecommerce/pull/3527&entry.1484655318=https://github.com/xitij2000&entry.752974735=2021-10-05+09:10&entry.1917517419=2022-08-11+12:46&entry.2133058324=No) so we can improve your experience in the future.

**Comment by pshiu** [comment]
@mzulqarnain1 We've included your PR upstream and the job that auto-updates requirements is working again. Thanks for help!

**Comment by pshiu** [comment]
Oops, meant to mention @xitij2000, see above!

**Pull request closed without merging**
