### PR TITLE
Added view exposing feature flags

### PR DESCRIPTION
**Pull request by clintonb**
ECOM-4854

### CODE REVIEW

**Comment by clintonb** [comment]
@bderusha @AlasdairSwan @Dillon-Dumesnil please review

**Comment by bderusha** [comment]
The code looks fine to me.  But I am wondering why it lives in ecommerce.  Wouldn't it make more sense for this to be controlled by the Catalog service?

**Comment by clintonb** [comment]
It lives here because this is the only IDA actively using Waffle. Additionally, I don't want to deal with the overhead of putting this in LMS.

**Comment by Dillon-Dumesnil** [comment]
Looks good minus failing the travis builds

**Comment by clintonb** [comment]
Related: https://github.com/edx/configuration/pull/3247

**Comment by bderusha** [comment]
👍

**Comment by clintonb** [comment]
Drat! Thanks for the review @bderusha; but, we've decided it's probably not a good idea to make a request to Otto for nearly every Drupal page load.

**Pull request closed without merging**
