### PR TITLE
chore: remove pytest-django-ordering

### PR DESCRIPTION
**Pull request by cmltaWt0**
Changes:
- re-generates requirements/dev.txt
- re-generates requirements/test.txt

https://github.com/edx/upgrades/issues/55#issuecomment-922457358

## Description

Package removed due to [pytest-django>=3.9](https://pytest-django.readthedocs.io/en/latest/changelog.html?highlight=ordering#id10) is used that has [required
plugin's logic](https://github.com/pytest-dev/pytest-django/blob/master/pytest_django/plugin.py#L366) to preserve the order of tests like Django test runner
does.

Useful information to include:
- https://github.com/edx/upgrades/issues/55#issuecomment-922457358

## Supporting information

- https://github.com/pytest-dev/pytest-django/issues/827
- https://github.com/pytest-dev/pytest-django/pull/830
- https://github.com/pytest-dev/pytest-django/pull/820

## Testing instructions

Run CI to ensure all tests passed and pytest-django-ordering plugin in not required for our TestSuit.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @cmltaWt0! I've created [OSPR-6059](https://openedx.atlassian.net/browse/OSPR-6059) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@cmltaWt0 Thank you for your contribution.  Is this ready for our review?

**Comment by cmltaWt0** [comment]
> @cmltaWt0 Thank you for your contribution. Is this ready for our review?

Yes. It's ready to review.

**Review by mraarif — APPROVED** [review]

**Comment by cmltaWt0** [comment]
PR has been rebased on master.

**Comment by openedx-webhooks** [comment]
@cmltaWt0 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/ecommerce&entry.867055334=https://github.com/edx/ecommerce/pull/3515&entry.1484655318=https://github.com/cmltaWt0&entry.752974735=2021-09-20+10:09&entry.1917517419=2021-10-29+06:47&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
