### PR TITLE
Migrate to karma-sabarivka-reporter

### PR DESCRIPTION
**Pull request by kopach**
Originally, this project (edx/ecommerce) was using `karma-coverage-allsources` to
include all project files under coverage statistic. However, this
package seems to be abandoned as well as close source and with security
issues https://snyk.io/test/npm/karma-coverage-allsources. With this commit, ecommerce
project now uses compatible open source alternative [karma-sabarivka-reporter](https://github.com/kopach/karma-sabarivka-reporter).
Which is writtent in TS, 100% tested and has no known security issues
https://snyk.io/test/npm/karma-sabarivka-reporter

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @kopach! I've created [OSPR-4131](https://openedx.atlassian.net/browse/OSPR-4131) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@kopach Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by kopach** [comment]
Thanks @natabene. However, I don't think this is for me. I'm not going to contribute to this repo in the nearest future, so don't see big reason in signing anything for open source for now. Feel free to reject my PR and made exactly the same changes yourself. It's easy to be done, there are no that many changes. It's totally fine with me. Thank you.

**Comment by natabene** [comment]
@kopach Thanks for clarifying. Unfortunately, we cannot accept any code without a signed agreement. We will try to implement your change as you suggested. Thanks!

**Comment by kopach** [comment]
Cool

**Comment by openedx-webhooks** [comment]
@kopach Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/ecommerce&entry.867055334=https://github.com/edx/ecommerce/pull/2822&entry.1484655318=https://github.com/kopach&entry.752974735=2020-02-29+17:18&entry.1917517419=2020-03-03+17:36&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
