### PR TITLE
Replace jquery-cookie with js-cookie

### PR DESCRIPTION
**Pull request by ahsan-ul-haq**
ECOM-2347
@tasawernawaz @jareerahsan @tasawernawaz please review

### CODE REVIEW

**Comment by ahsan-ul-haq** [comment]
@clintonb I have replaced jquery-cookie with js-cookie but there are some failing tests which I can't understand why. Could you help me with that?

**Comment by clintonb** [comment]
What steps have you taken to debug locally?

**Comment by ahsan-ul-haq** [comment]
@clintonb @AlasdairSwan please review.

**Comment by clintonb** [comment]
:+1:

**Comment by tasawernawaz** [comment]
👍

**Comment by AlasdairSwan** [comment]
Nice 👍

**Pull request merged**
