### PR TITLE
Update Coupon offer landing page to support discount

### PR DESCRIPTION
**Pull request by vkaracic**
When a user goes to a link with an discount code passed as a query string parameter information about the course, price, discount and link to add the course to the basket. The new basket is still a work in progress and therefor the link is currently disabled. 
Additionally the LMS footer is displayed for all the coupon templates.

screenshot from 2016-02-03 15-07-53

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=529

**Comment by vkaracic** [comment]
@marjev  @mjfrey please take a look.

**Comment by mjfrey** [comment]
:+1:  Once all tests pass.

**Comment by marjev** [comment]
:+1:

**Pull request merged**
