### PR TITLE
Improve extensibility for custom server-side payment processors

### PR DESCRIPTION
**Pull request by regisb**
Implementing a custom server-side payment processor is a process that suffers from a few minor, but quite annoying issues. In this pull request we address the following issues:

1. Remove unsafe yaml loading warning coming from production settings
2. Fix empty checkout button for custom server-side payment processors
3. Add custom urls for custom payment processors. This is useful, e.g: for callbacks.
4. Fix http/https url scheme for those people who don't run ecommerce with https in production. This might happen, when running locally, for instance.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @regisb! I've created [OSPR-4941](https://openedx.atlassian.net/browse/OSPR-4941) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@regisb Thank you for your contribution. Please let me know once this is ready for our review.

**Comment by regisb** [comment]
@natabene this is ready to be reviewed :) There is just one item which is unclear to me: as I updated one of the templates, I re-generated the translation files and added the missing translation. But the `py38-django22-detect_changed_translations` tox job is failing on Travis CI, so I guess I must have done something wrong -- but I don't know what.

**Comment by natabene** [comment]
@regisb Thanks for letting me know. I am not sure what to do with the test failure, @nedbat Any advice?

**Comment by regisb** [comment]
Hello? ;)

**Comment by natabene** [comment]
@jmbowman Would you be able to help us here with the tests?

**Comment by jmbowman** [comment]
The latest docs I can find on this are at https://openedx.atlassian.net/wiki/spaces/ENG/pages/146440742/Automated+Translation+Management .  Did you update the translations via `make fake_translations` as recommended there?

**Comment by jmbowman** [comment]
Ah, it looks like you don't have permission to view that page.  Here's the relevant section:

> For course-discovery, ecommerce, credentials, and credentials-themes, developers are responsible for updating source translations with each change that will be merged to master. This is enforced by Travis, which calls a make target to check if the translations are out-of-date. The course-discovery, ecommerce, and credentials repos use the check_translations_up_to_date make target for this. When translations are found to be out-of-date (look for a message in the build log that reads something like "Source translations are out-of-date! Please update them."), developers should run a make command to update them. For course-discovery, ecommerce, and credentials, the fake_translations command should be used for this. For credentials-themes, the generate_translations command should be used.

**Comment by regisb** [comment]
@jmbowman I think I may have run only `extract_translations` (which is a part of `fake_translations`). Did this just now.

May I suggest someone moves private docs from Jira to `docs/`? I can do it if I am granted access.

**Comment by regisb** [comment]
Can someone please help me merge this before Koa?

**Comment by jmbowman** [comment]
I copied the parts of that doc that are relevant to non-edX employees to https://openedx.atlassian.net/wiki/spaces/AC/pages/1984790989/Translation+Management (although there isn't much to it beyond what I quoted above).  From the failing Travis job, it looks like you should be able to get more details by running `tox -e py38-django22-validate_translations` locally and checking the generated `.prob` file.

**Comment by marcotuts** [comment]
@regisb  - I wanted to follow up here that I don't think this will be able to merge before Koa is cut. The team is aware of the work and can prioritize, but the contribution is large enough and sensitive enough that the review can't be completed by the 11/9 cut off. (FYI @natabene, @sethmccann ) 

If this is the kind of candidate ticket to make it into a patch for Koa in the future we can discuss this once merged / later but I wanted to set expectations as soon as I saw this fly by and connected wit the team. 

Excited to see the commerce tool move toward pluggability with this contribution!

**Comment by regisb** [comment]
@marcotuts this is really too bad, as the changes in this PR are in fact quite minor in terms of impact on the code base, but allow for considerably better extensibility. For instance, these changes were required to create an integration with the Swiss Saferpay payment backend: https://github.com/epfl-cede/openedx-saferpay

**Comment by regisb** [comment]
Can I expect a review of this before the year is over? It's been two months already...

**Comment by sethmccann** [comment]
@regisb Thanks for the contribution, we'll have time to review this in early Jan.

**Comment by regisb** [comment]
> we'll have time to review this in early Jan.

@sethmccann We are now in February. When can I expect a review? Is there an issue with the improvements proposed here?

**Comment by sethmccann** [comment]
@regisb Apologies for the delay, I hope to fit it in next sprint beginning 2/17.

**Review by inventhouse — APPROVED** [review]

**Comment by inventhouse** [comment]
@regisb I'm sorry this too so long to review, but it looks good; I think you'll need to resolve the merge conflicts by regenerating the translation files (I don't think I can do that on your fork), but as soon as that's done, I will merge this quickly.

**Comment by regisb** [comment]
Thanks for the review @inventhouse! I rebased my changes and re-generated the translation files.

**Comment by openedx-webhooks** [comment]
@regisb 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/ecommerce&entry.867055334=https://github.com/edx/ecommerce/pull/3140&entry.1484655318=https://github.com/regisb&entry.752974735=2020-09-03+15:18&entry.1917517419=2021-02-22+16:14&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
