### PR TITLE
Displaying provider name instead of ID on credit checkout page 

### PR DESCRIPTION
**Pull request by clintonb**
ECOM-2172

@rlucioni @jimabramson

### CODE REVIEW

**Comment by rlucioni** [comment]
:+1:

**Comment by jimabramson** [comment]
:+1:  no objections, but as an aside, curious why the text needs to be upper'd.

**Comment by clintonb** [comment]
@jimabramson 
screencapture-ecommerce-stage-edx-org-credit-checkout-course-v1-3aasux-2bcreditdemo-2bdemo_course-1442501728182

**Comment by wedaly** [comment]
Why are we showing the provider ID here rather than the provider's display name?

**Comment by jimabramson** [comment]
@clintonb thanks for the visual explanation :-)

**Comment by clintonb** [comment]
@wedaly I'm just fixing an error I saw. Product is out, and this needs to hit stage before 1 PM. Any preference on ID vs name? I can defend either.

**Comment by wedaly** [comment]
@clintonb If it's not additional work, I'd prefer the name.  Uppercasing the ID could bite us down the road if we add an additional provider.

**Comment by clintonb** [comment]
Agreed. Consider it done.
\

**Comment by clintonb** [comment]
Updated to use display name instead of ID.

**Comment by rlucioni** [comment]
:+1:

**Pull request merged**
