### PR TITLE
Synchronous order fulfillment for free baskets.

### PR DESCRIPTION
**Pull request by vkaracic**
It doesn't make sense to keep a user waiting for an async process to finish just so the result from that process can be used to determine where to send the user. That whole use case is synchronous vulgaris and should be executed as such.
Not to mention that the _enrollment code applied > checkout > receipt page_ flow would work with this as opposed to the [last few tries](https://github.com/edx/ecommerce/pull/1149).

https://openedx.atlassian.net/browse/SOL-2073

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=1187"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Review by clintonb — CHANGES_REQUESTED** [review]
We added asynchronous fulfillment to avoid tying up all of our gunicorn workers on LMS with two requests for the same enrollment call.

What problem is this change trying to resolve?

This will need to be load-tested (before and after this change) to ensure this does not lead to performance degradation.

**Review by mjfrey — CHANGES_REQUESTED** [review]
I do not think we should do this.  During large coupon based campaigns this will be a problem bypassing the async order fulfillment.  We need to figure out why the receipt page approach was not working.

**Comment by vkaracic** [comment]
@clintonb the problem it's trying to solve is redirecting a user to a receipt page if the order fulfillment was successful or the checkout error page if it wasn't. The previous tries (https://github.com/edx/ecommerce/pull/1149) don't work on stage, they all timeout (event the last 10 seecond timeout).

**Comment by clintonb** [comment]
If there is an issue creating the order, go to the checkout error page. After an order has been created, go to the receipt page. If the order has not been fulfilled, display a message to the user and poll the system until the order is fulfilled or there is an error. If there is a fulfillment error, display a message to that effect.

**Pull request closed without merging**
