### PR TITLE
Add support for course catalog pagenated results

### PR DESCRIPTION
**Pull request by mjfrey**
Get all paginated results from course catalog.

### CODE REVIEW

**Comment by mjfrey** [comment]
@marjev @vkaracic

**Comment by mjfrey** [comment]
@bderusha

**Comment by mjfrey** [comment]
@mattdrayer

**Comment by mattdrayer** [comment]
These `while` loops seem unnecessary to me -- in a server-to-server context, I see no problem with simply bumping up the size of the response payload to include all records, using a value of say, 10000.  We can get what we need in a single network request, and doing so eliminates the need to introduce the new logic, which seems like it would be better to locate in the EdxRestApiClient, anyway.

**Comment by mjfrey** [comment]
ok, I will close this PR out in favor of just bumping up the limit in the API call to the Catalog Service.

**Comment by bderusha** [comment]
Sounds good

**Pull request closed without merging**
