### PR TITLE
Updated payment processor switch signal receiver

### PR DESCRIPTION
**Pull request by clintonb**
- Using `cache.delete` rather than `caches['default']`
- Added tests

### CODE REVIEW

**Comment by clintonb** [comment]
@edx/ecommerce please review

**Comment by clintonb** [comment]
FYI @jibsheet

**Review by rlucioni — CHANGES_REQUESTED** [review]
@clintonb these switches don't appear to actually be used on the newer checkout page hosted by Otto. Even if we were to update the page so that these switches are respected, I don't think this caching makes much sense anymore given Waffle's caching of the switch values.

**Review by rlucioni — APPROVED** [review]
However, 👍 for fixing the code itself, even if it's dead. Could you at least add a TODO comment so that our conversation here isn't lost? You could even link to this PR.

**Pull request merged**
