### PR TITLE
added comments about the upcoming deprecation of old sdnCheck code

### PR DESCRIPTION
**Pull request by dianekaplan**
Adding a heads up about the code we'll be removing. See deprecation ticket here: 
https://openedx.atlassian.net/browse/DEPR-90

### CODE REVIEW

**Review by julianajlk — CHANGES_REQUESTED** [review]
Can you add the DPR ticket number on your comment?

**Comment by dianekaplan** [comment]
> Can you add the DPR ticket number on your comment?

good call- added now!

**Review by julianajlk — APPROVED** [review]
Meant on your comment in the code, so that people that don't know the context or the PR can reference if they come across it in the code.

**Comment by dianekaplan** [comment]
> Meant on your comment in the code, so that people that don't know the context or the PR can reference if they come across it in the code.

good idea- added now!

**Pull request merged**
