### PR TITLE
ENT-3622 | Reverting the management command to the original code afte…

### PR DESCRIPTION
**Pull request by hasnain-naveed**
…r doing the testing.

### CODE REVIEW

**Comment by moconnell1453** [comment]
jenkins run all

**Comment by julianajlk** [comment]
Jenkins run all

**Comment by julianajlk** [comment]
jenkins run py38 python

**Comment by hasnain-naveed** [comment]
jenkins run all

**Comment by hasnain-naveed** [comment]
These changes have been merged before I reverted these for test purposes.

**Review by saleem-latif — APPROVED** [review]

**Review by sameenfatima78 — APPROVED** [review]

**Pull request merged**
