### PR TITLE
Pin python-social-auth

### PR DESCRIPTION
**Pull request by mjfrey**
Pin python-social-auth==0.2.14

### CODE REVIEW

**Comment by mjfrey** [comment]
@clintonb @rlucioni

**Comment by rlucioni** [comment]
Could you please add a comment linking to https://github.com/omab/python-social-auth/pull/897? It should be possible to remove the pin once the changes in that PR are released.

**Comment by mjfrey** [comment]
@rlucioni comment added.

**Comment by clintonb** [comment]
:+1:

**Comment by rlucioni** [comment]
👍

**Pull request merged**
