### PR TITLE
Fix for LEARNER-6529 Can't edit coupons with fixed prices

### PR DESCRIPTION
**Pull request by raeeschachar**
https://openedx.atlassian.net/browse/LEARNER-6529

### CODE REVIEW

**Review by Ayub-Khan — APPROVED** [review]

**Comment by raeeschachar** [comment]
@staubina @robrap  can you review and merge this PR? Waheed is out on leaves, you are part of ecommerce-guild I think.

**Comment by robrap** [comment]
@raeeschachar @Ayub-Khan: @bill-filler is going to review this.  Thanks!

**Comment by raeeschachar** [comment]
Thanks for the heads up @robrap

**Review by bill-filler — APPROVED** [review]
tested it out, works as expected

**Comment by raeeschachar** [comment]
Awesome, thanks @bill-filler

**Comment by robrap** [comment]
@raeeschachar: Thank you for this.  We've got a potential fix to the errors affecting this PR (and all ecommerce PRs) going through tomorrow, and then we'll have @bill-filler follow-up with this.
FYI: @jmyatt: Who is working on the ecommerce errors.

**Pull request merged**
