### PR TITLE
Fix wrong Professional Field Template location

### PR DESCRIPTION
**Pull request by dwisulfahnur**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @dwisulfahnur! I've created [OSPR-2944](https://openedx.atlassian.net/browse/OSPR-2944) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@dwisulfahnur  Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions.

**Comment by dwisulfahnur** [comment]
Hello Natalia,

I have sent my ICLA to this email legal@edx.org, but there was no response
from it.

Thanks

**Comment by natabene** [comment]
HI Dwi,

thank you for sending the signed agreement. edX office was closed for
winter holidays.
Legal team will process your agreement as soon as possible, and will let
you know once it is done.
Please stay tuned for updates.

Best,
Natalia

Natalia Berdnikov
edX | Senior Project Manager
141 Portland Street, 9th Floor
Cambridge, MA 02139
nberdnikov@edx.org
http://www.edx.org

**Comment by natabene** [comment]
@dwisulfahnur  Thank you for joining the Open edX community! We have added your user to our records and can now review your code going forward. 
For this PR, can you let me know once you have provided a description and also once it passes all tests? We then will start the review process. Thanks!

**Comment by natabene** [comment]
@dwisulfahnur I am curious if you are still interested in pursuing this. If yes, can you provide a description, mentioned earlier, and fix the failing test? Thanks

**Comment by edx-webhook** [comment]
Thanks for the pull request, @dwisulfahnur! I've created [OSPR-3580](https://openedx.atlassian.net/browse/OSPR-3580) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by edx-webhook** [comment]
Thanks for the pull request, @dwisulfahnur! I've created [OSPR-3582](https://openedx.atlassian.net/browse/OSPR-3582) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@dwisulfahnur Could you please provide description for this PR? Thanks.

**Comment by natabene** [comment]
@dwisulfahnur We have not heard from you in while so I am closing this PR for now. Please feel free to re-open if you decide to pick this up again.

**Comment by openedx-webhooks** [comment]
@dwisulfahnur Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/ecommerce&entry.867055334=https://github.com/edx/ecommerce/pull/2086&entry.1484655318=https://github.com/dwisulfahnur&entry.752974735=2018-12-31+18:59&entry.1917517419=2019-07-24+17:56&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
