### PR TITLE
Increase enrollment fulfillment timeout

### PR DESCRIPTION
**Pull request by rlucioni**
It's [considered good practice](http://docs.python-requests.org/en/latest/user/advanced/#advanced) to set connection timeouts to slightly larger than a multiple of 3, the default TCP packet retransmission window. Bumping the connection timeout from 5 to 7 will get us an extra retry we didn't have before.

This change is meant to alleviate enrollment revocation timeouts described in [XCOM-424](https://openedx.atlassian.net/browse/XCOM-424). I'll be following this up with LMS changes. @jimabramson or @clintonb, please review.

### CODE REVIEW

**Comment by jimabramson** [comment]
:+1:

**Comment by clintonb** [comment]
:+1:

**Comment by clintonb** [comment]
Will configuration changes be needed? Is this value overridden?

**Comment by rlucioni** [comment]
@clintonb no, this setting is not present in edx/configuration.

**Pull request merged**
