### PR TITLE
[WIP] Change receipt page to be a Backbone view

### PR DESCRIPTION
**Pull request by vkaracic**
@clintonb this is very much still a work in progress but please take a look and let me know if I'm on the right track, and if this is inline with your [comment](https://github.com/edx/ecommerce/pull/1187#issuecomment-284720747).

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @vkaracic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1202&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by clintonb** [comment]
You should not redirect to the receipt page unless there is an order. What's the waiting for? The only payment processor for which we have to wait is CyberSource. There should be no waiting there because we should be using the interstitial from https://github.com/edx/ecommerce/pull/1025.

I am personally not a fan of client-side rendering, especially for static pages like this. Why does the page need to be converted to Backbone? (FYI we are switching to React according to https://github.com/edx/open-edx-proposals/pull/32)

**Comment by vkaracic** [comment]
There is always an order, this is for when a user applies an enrollment code in which case it circumvents any payment and goes directly to the receipt page (currently it redirects the user to the dashboard, but the intention was to redirect to the receipt page). Since the order is fulfilled asynchronously it could take some time before we know if it's complete or there was a fulfillment error, and since an approach like [this one](https://github.com/edx/ecommerce/pull/1149) does not work, this is the alternative I've came up with.

**Comment by clintonb** [comment]
I offer a simpler approach that doesn't involve overhauling the receipt page unnecessarily. As with Cybersource, redirect to an interstitial that waits for the order to reach certain states. Once those states are reach redirect to the final page in the flow—receipt or error.

**Comment by vkaracic** [comment]
Can you point out to me where exactly does the Cybersource interstitial view _wait_ for something?

**Comment by clintonb** [comment]
The wait is not an asynchronous poll. The data that gets POSTed by CyberSource is used to create the order synchronously. After it's created, the user is redirected.

**Comment by vkaracic** [comment]
The order is created synchronously, but fulfilled asynchronously, same as it is here.

**Comment by clintonb** [comment]
Back up. We don't necessarily care about fulfillment here. Free orders are created immediately, so it should be safe to go straight to the receipt.

Why are we treating enrollment code orders differently from any other order?

**Comment by vkaracic** [comment]
So we can display the receipt page even if the order has not been fulfilled (in this case the user enrolled in the course) or there was a fulfillment error?

**Comment by clintonb** [comment]
Yes. The receipt page doesn't care about the order's status.

**Comment by mjfrey** [comment]
But there are cases where an enrollment code was used but not successful.  For that reason, checking the order status is necessary.

**Comment by clintonb** [comment]
Define "not successful". If the enrollment code cannot be redeemed, an order should not be created. If the order is created, but not fulfilled, that is a separate issue.

**Comment by mjfrey** [comment]
Yes I am talking about the later.  There are times when an enrollment code (free order) is used for a professional course for example.  But fulfillment can not happen.  Today The learner is just taken to the dashboard with no indication of success or failure.

**Pull request closed without merging**
