### PR TITLE
ENT-3084: Updated email API to handle email subject.

### PR DESCRIPTION
**Pull request by saleem-latif**
**Jira Ticket:** [ENT-3084](https://openedx.atlassian.net/browse/ENT-3084)

**Description:**
As an enterprise admin, I want to be able to change the subject line of the code assignment email I send.
This PR adds the new email subject field in the email template model and the API.

### CODE REVIEW

**Review by HammadAhmadWaqas — APPROVED** [review]

**Comment by hasnain-naveed** [comment]
How was it working before this? Was it a hardcoded subject?

**Comment by saleem-latif** [comment]
@hasnain-naveed The subject is still being hardcoded, I will update that part after making the frontend change, otherwise code assignment code will raise a 500 error.
This PR only contains the API and model changes.

**Review by hasnain-naveed — APPROVED** [review]

**Comment by muhammad-ammar** [comment]
@saleem-latif Can you please share the rollout plan? I think there will be multiple releases/PRs for this work?

**Comment by saleem-latif** [comment]
@muhammad-ammar I will first merge this PR then the front end work will go and finally I will update the backend with the rest of the changes.

**Review by muhammad-ammar — APPROVED** [review]

**Pull request merged**
