### PR TITLE
Fix acceptance/end-to-end tests

### PR DESCRIPTION
**Pull request by rlucioni**
Fixes include: interacting with the iframe on PayPal's new login page, updates to deal with the new edX checkout page, loading the edX receipt page several times to deal with slow payment processing, more robust interaction with the coupon admin app, and allowing coupon admin tests to be skipped (which they are, by default).

@schenedx @jimabramson @ronaldmulero @mjfrey FYI

### CODE REVIEW

**Comment by clintonb** [comment]
>  ...and allowing coupon admin tests to be skipped (which they are, by default).

Why are these tests skipped?

**Comment by rlucioni** [comment]
@clintonb they can be skipped because the same functionality is covered by the coupon checkout tests. I've left the admin tests in place for now because I'm not sure if there's benefit to being able to run them independently. If they need to be removed, I'd prefer that be done separately. There was talk of using an API to create coupons during the checkout tests, in which case the admin tests would become useful again.

**Comment by clintonb** [comment]
I made the recommendation of correcting the checkout tests. They should definitely be using the API rather than the UI. Please file a SOL ticket so that this can be fixed.

**Comment by rlucioni** [comment]
@clintonb see [SOL-1775](https://openedx.atlassian.net/browse/SOL-1775).

**Comment by mjfrey** [comment]
For completeness I created  [ECOM-4319](https://openedx.atlassian.net/browse/ECOM-4319).  As there currently are no acceptance tests for the Course Admin Tool.

**Pull request merged**
