### PR TITLE
Removed docs compilation from Travis

### PR DESCRIPTION
**Pull request by clintonb**
The docs compilation breaks coverage.

### CODE REVIEW

**Comment by clintonb** [comment]
FYI @rlucioni @jimabramson @bderusha @peter-fogg

**Comment by rlucioni** [comment]
:+1:

**Comment by peter-fogg** [comment]
:+1:, but why does it break coverage?

**Comment by clintonb** [comment]
@peter-fogg I don't know. However, I have updated the commit to do docs compilation before validation. I suspect something in docs compilation is deleting the coverage output. Let's see if that is true.

**Pull request merged**
