### PR TITLE
[BD-6] Run tests in python 3.8

### PR DESCRIPTION
**Pull request by morenol**
Run and fix tests in python3.8.

This chages were done in order to pass the tests:

Specify version of django used in several tox commands like: validate_translations,  extract_translations, compile_translations... because in python 3.8 if that is not define it uses Django3.0 which is currently failing.

Change tests to use the right representation of the exception of the version of python (Changed in python 3.7) https://bugs.python.org/issue30399

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @morenol! I've created [OSPR-4539](https://openedx.atlassian.net/browse/OSPR-4539) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by morenol** [comment]
This is now passing the tests @awais786 ,

But it has this in the travis install part:
```bash
sudo add-apt-repository ppa:deadsnakes/ppa -y;
sudo apt-get update -y;
sudo apt-get install python3.8 python3.8-distutils python3.8-dev -y;"
```

I am not sure if we have to wait until the docker image have these packages installed by default.

**Comment by awais786** [comment]
> This is now passing the tests @awais786 ,
> 
> But it has this in the travis install part:
> 
> ```shell
> sudo add-apt-repository ppa:deadsnakes/ppa -y;
> sudo apt-get update -y;
> sudo apt-get install python3.8 python3.8-distutils python3.8-dev -y;"
> ```
> 
> I am not sure if we have to wait until the docker image have these packages installed by default.

@morenol  edX is running a/b tests on the checkout page starting Monday of the upcoming week from 18th to 26th. So lets wait for 1 week on this PR. 
@jmbowman Please review.

**Comment by morenol** [comment]
I removed the installation of the python 3.8 packages since the image used in the tests now has that installed.

**Comment by jmbowman** [comment]
The ecommerce experiment that was blocking most merges has ended.  Was that holding this back, or are there other issues left to sort out?

**Comment by morenol** [comment]
> The ecommerce experiment that was blocking most merges has ended. Was that holding this back, or are there other issues left to sort out?

@jmbowman not as far as I know, I am going to rebase this.

**Review by awais786 — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@morenol 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/ecommerce&entry.867055334=https://github.com/edx/ecommerce/pull/2943&entry.1484655318=https://github.com/morenol&entry.752974735=2020-05-14+15:11&entry.1917517419=2020-06-02+15:50&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
