### PR TITLE
Changed requirements to pull edx-i18n-tools from PyPI and .gitignore …

### PR DESCRIPTION
**Pull request by Dillon-Dumesnil**
…to include en files

@clintonb @bderusha please review

### CODE REVIEW

**Comment by clintonb** [comment]
Remember to commit the English files, too.

**Comment by clintonb** [comment]
👍

**Comment by iivic** [comment]
@clintonb @mjfrey Please review and confirm merge.

**Comment by iivic** [comment]
@clintonb I generated the English files with command "make fake_translations". Are those the required English files and what is their purpose?

**Comment by clintonb** [comment]
@iivic the goal of this work is to allow Transifex to automatically pull the strings that need to be translated. The English source files contain those strings. Only the .po files should be committed.

**Comment by iivic** [comment]
Thank you for the context. It makes more sense now. I removed the .mo files. 
Review once more...

**Comment by clintonb** [comment]
There were errors with the first commit, the .mo files _do_ need to be included. I have fixed this and rebased.

👍

**Pull request merged**
