### PR TITLE
WL-469: Basket update quantity button ui fixed.

### PR DESCRIPTION
**Pull request by malikshahzad228**

### CODE REVIEW

**Comment by malikshahzad228** [comment]
ScreenShots:

screen shot 2016-05-17 at 5 03 32 pm

screen shot 2016-05-17 at 5 08 23 pm

screen shot 2016-05-17 at 5 09 21 pm

**Comment by malikshahzad228** [comment]
@mattdrayer FYI

**Comment by mattdrayer** [comment]
Looks good -- thanks for including the screenshot -- 👍  to merge after rebase and green build

**Comment by malikshahzad228** [comment]
@mattdrayer Rebased and Build is passed.
Merging Now.

**Pull request merged**
