### PR TITLE
Fix duplicate Condition bug

### PR DESCRIPTION
**Pull request by tuchfarber**
If a condition with the program_uuid that you are trying to update to already exists, don't update it so we don't get duplicates.

### CODE REVIEW

**Review by robrap — COMMENTED** [review]
Could you add a test? Thanks.

**Comment by robrap** [comment]
@tuchfarber: Is this tied to a ticket that we can follow?  Is this a bug that should be fixed?  Other?  Thanks.

**Comment by tuchfarber** [comment]
Sorry about this. It's a bug that should be fixed. I backburnered it for a couple days then completely forgot about it. 

The bug is: 
`_get_or_create_offer` assumes 1 coupon per program.

This method (`update_coupon_offer`) allows you to change a program offer to a program_uuid that already exists, thus breaking the _get_or_create_offer call later in the function. Unsure if these transactions are atomic or not. If not, it would leave the offers in a broken state. 

I can put in an ecomm-guild ticket if you want.

**Comment by robrap** [comment]
Ecommerce transactions are atomic by default. Not sure if you saw a problem occur, or just saw a potential problem in the code. Either way, would you mind creating a ticket so we can better track this? Thank you.

**Comment by feanil** [comment]
This code was updated differently by other work and this line no longer exists.  It looks like it moved over here: https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/voucher/utils.py

and now does a get or create.

**Pull request closed without merging**
