### PR TITLE
Caching Node and Bower Dependencies

### PR DESCRIPTION
**Pull request by clintonb**
This should cut Travis CI build times by at least a minute.

FYI @jimabramson @rlucioni @Nickersoft

### CODE REVIEW

**Comment by rlucioni** [comment]
This seems to have added a minute to the build time.

**Comment by clintonb** [comment]
@rlucioni I don't believe so. Build times have been around 9 minutes for the last couple days. In any case, only _subsequent_ builds will take advantage of the caching.

**Comment by rlucioni** [comment]
:+1:

**Comment by jimabramson** [comment]
:+1:

**Comment by clintonb** [comment]
We got some speedups; but, there is room to improve. Specifically, we need to figure out how to cache lxml, pillow (which should really be removed), and libsass.

**Pull request merged**
