### PR TITLE
E0d/new coupon category

### PR DESCRIPTION
**Pull request by e0d**
Create a new coupon category.

### CODE REVIEW

**Comment by e0d** [comment]
@georgebabey @feanil quick review?

**Comment by e0d** [comment]
@cpennington should have added you as guild elder.

**Comment by cpennington** [comment]
I mean, it looks reasonable to me. But I can't claim to have done this before.

**Review by cpennington — APPROVED** [review]

**Review by georgebabey — APPROVED** [review]

**Comment by georgebabey** [comment]
Reasonable other than the update for emacs :trollface:

**Pull request merged**
