### PR TITLE
Extra Footer removed

### PR DESCRIPTION
**Pull request by malikshahzad228**
@mattdrayer FYI

I removed the get_lms_footer from all places. Let me know your thoughts.

### CODE REVIEW

**Comment by mattdrayer** [comment]
I'm good with this change -- @saleem-latif @douglashall, let us know what you think as well -- looks like the branch needs a rebase and there are some failing tests looking for the now-missing 'footer' context key.

**Comment by clintonb** [comment]
How does this change affect edx.org? Please post a screenshot.

**Comment by mattdrayer** [comment]
@clintonb, we're going to be adding a footer template to edx/edx-themes/ecommerce/edx.org to cover the case you've highlighted.

**Comment by malikshahzad228** [comment]
@mattdrayer Default footer for edx.org theme is added, [PR is here](https://github.com/edx/edx-themes/pull/15).

**Comment by mattdrayer** [comment]
Great, can you post the screenshots from the JIRA ticket for @clintonb to see?

**Comment by malikshahzad228** [comment]
edx org_footer
otto_footer

@mattdrayer @clintonb and this behaves same in terms of responsive.

**Comment by mattdrayer** [comment]
Also, we still need to fix the broken tests and rebase the branch

**Comment by mattdrayer** [comment]
@malikshahzad228 -- great to see the tests are passing!  But, it looks like we need another rebase :)

**Comment by malikshahzad228** [comment]
@mattdrayer rebased, travis looks happy as well.

**Comment by malikshahzad228** [comment]
@mattdrayer travis looks happy now.

**Comment by mattdrayer** [comment]
👍 !!!

**Comment by mattdrayer** [comment]
https://github.com/edx/edx-themes/pull/15

**Comment by malikshahzad228** [comment]
@douglashall FYI

**Comment by douglashall** [comment]
👍 Need to rebase again. :(

**Pull request merged**
