### PR TITLE
Reorganized API View Tests

### PR DESCRIPTION
**Pull request by clintonb**
The tests have been split by resource (e.g. basket, order, refund). This should help improve the readability and maintainability of the tests.

XCOM-505

@rlucioni @jimabramson @Nickersoft

### CODE REVIEW

**Comment by rlucioni** [comment]
:+1:

**Comment by jimabramson** [comment]
minor: could the "test_views" directory simply be named "views" ?

either way :+1:

**Comment by clintonb** [comment]
@jimabramson it turns out, yes, the `test_views` module can be renamed to `views`. I guess it's only the child module (e.g. `test_baskets`) that needs the `test_` prefix.

**Comment by jimabramson** [comment]
@clintonb nice.

**Pull request merged**
