### PR TITLE
Capture acceptance test results in an xunit.xml file.

### PR DESCRIPTION
**Pull request by benpatterson**
This will allow test results to be more easily consumed by:
- CI infrastructure
- A developer who wants to understand results
- Logging infrastructure we use wherein we can roll together test results across repos

### CODE REVIEW

**Comment by benpatterson** [comment]
@rlucioni @schenedx 

I'd like to capture test results from this repo in an xunit file, which we can then feed into Jenkins output for usability, trending, etc.

**Comment by rlucioni** [comment]
👍

**Comment by schenedx** [comment]
:+1: @benpatterson Are you going to make the same change for Programs IDA at https://github.com/edx/programs/blob/master/Makefile? Thanks

**Comment by benpatterson** [comment]
@schenedx Yep...that's my plan!

**Pull request merged**
