### PR TITLE
chore: upgrade Django to 3.2.21

### PR DESCRIPTION
**Pull request by magajh**
See: https://github.com/openedx/wg-build-test-release/issues/303

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @magajh! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @openedx/revenue-squad! Would someone be able to please review/merge this for us?

**Comment by mphilbrick211** [comment]
> Hi @openedx/revenue-squad! Would someone be able to please review/merge this for us?

hi @openedx/revenue-squad! Could you please provide an ETA on getting this reviewed?

**Comment by magajh** [comment]
@mphilbrick211 thanks for the follow-up!

We are closing this PR as we're now focusing on applying the Django 3.2.23 security patch. This is to ensure we're using the latest and most secure Django version for the Palm release.

For more details: https://github.com/openedx/wg-build-test-release/issues/306.

**Comment by magajh** [comment]
@mphilbrick211 thanks for the follow-up!

We are closing this PR as we're now focusing on applying the Django 3.2.23 security patch. This is to ensure we're using the latest and most secure Django version for the Palm release.

For more details: https://github.com/openedx/wg-build-test-release/issues/306.

**Comment by openedx-webhooks** [comment]
@magajh Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/ecommerce&entry.867055334=https://github.com/openedx/ecommerce/pull/4028&entry.1484655318=https://github.com/magajh&entry.752974735=2023-09-08+13:16&entry.1917517419=2023-11-14+23:51&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@magajh Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/ecommerce&entry.867055334=https://github.com/openedx/ecommerce/pull/4028&entry.1484655318=https://github.com/magajh&entry.752974735=2023-09-08+13:16&entry.1917517419=2023-11-14+23:51&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
