### PR TITLE
Fix for ECOM-3321 flaky test

### PR DESCRIPTION
**Pull request by mjfrey**
Attempt to fix flaky test for ECOM-3321

### CODE REVIEW

**Comment by mjfrey** [comment]
@rlucioni This is to skip the test for ECOM-3321.

**Comment by rlucioni** [comment]
FYI @peter-fogg

**Comment by rlucioni** [comment]
:+1: after commits are squashed.

**Comment by clintonb** [comment]
If this test is not going to be run, we should just remove it. There's is no point to keeping dead code around.

**Comment by peter-fogg** [comment]
@clintonb I'd prefer keeping the test with `xit` for now, and prioritizing an actual fix.

**Comment by mjfrey** [comment]
We are going to be changing this a bit so the test will be used in the future.

**Comment by clintonb** [comment]
Okay.

**Pull request merged**
