### PR TITLE
upgrade the djangorestframework and drf-extensions

### PR DESCRIPTION
**Pull request by mraarif**
This [PR](https://github.com/edx/ecommerce/pull/2802) was reverted a few days ago due to e2e failures that were probably unrelated.  This PR reverts the revert.

Note: this work is more closely related to [BOM-1318](https://openedx.atlassian.net/browse/BOM-1318).

### CODE REVIEW

**Comment by robrap** [comment]
@mraarif: Consider adding "BOM-1318" to the commit comment as well.  Thank you.

**Comment by mraarif** [comment]
@robrap I've added the link for the relevant issue.

**Comment by mraarif** [comment]
I think `httpretty` needs to be constrained as done in master.

**Review by robrap — APPROVED** [review]
I'm assuming this the original code that was already approved, and you are just working on getting `make upgrade` updated and a green build.  Let me know if you need anything else in particular reviewed.  Thanks.

Ecommerce is open for merges and deploys again.

**Comment by mraarif** [comment]
Thanks, @robrap , you're right there are no additional changes in this PR.

**Pull request merged**
