### PR TITLE
Add a threshold of errors before flunking verify_transactions

### PR DESCRIPTION
**Pull request by inventhouse**

### CODE REVIEW

**Review by MatthewPiatetsky — CHANGES_REQUESTED** [review]
it looks like this will simply not error when there are fewer errors than the threshold? i believe we said that we want to be alerted with a high priority if the error is above a certain threshold, but i think we said we didn't want to completely stop getting informed of problematic transactions until we have another way to handle them?

**Comment by inventhouse** [comment]
> it looks like this will simply not error when there are fewer errors than the threshold? i believe we said that we want to be alerted with a high priority if the error is above a certain threshold, but i think we said we didn't want to completely stop getting informed of problematic transactions until we have another way to handle them?

As far as I can tell, Jenkins jobs either alert-or-not; the plan is to add a second job that alerts on any change and make that a P2 or have it just go to Customer Support directly.  That said, perhaps the default threshold ought to be `0` so the leniency is more explicit.

**Review by MatthewPiatetsky — APPROVED** [review]
assuming a threshold of 0 means that for now it will continue to alert on the same errors until we have an alternate plan for them

**Review by emma-green — APPROVED** [review]
looks good to me -- let's checkin with Shelby about appropriate threshold and communicating with learner support.

**Pull request merged**
