### PR TITLE
Fix for new offer landing page.

### PR DESCRIPTION
**Pull request by mjfrey**
New offer landing page is a tad slower so we need to wait for the elements on the page.

### CODE REVIEW

**Comment by mjfrey** [comment]
@mattdrayer

**Comment by mattdrayer** [comment]
👍, assuming the IDs included in this PR correctly match those in the template!

**Comment by mjfrey** [comment]
No ID's changed.  Just the page take a bit longer to load.

**Comment by mattdrayer** [comment]
While this is definitely an acceptable approach, I think there's a better way to wait for an element to appear using Promises, EmptyPromises, and BrokenPromises (sounds like a bad country song)

**Pull request merged**
