### PR TITLE
Sending Course ID to Segment/Google Analytics

### PR DESCRIPTION
**Pull request by clintonb**
Marketing requests that the course ID be sent instead of the product title.

ECOM-2005

### CODE REVIEW

**Comment by clintonb** [comment]
@jimabramson @rlucioni

**Comment by rlucioni** [comment]
`ecommerce/extensions/refunds/signals.py` should also be updated to send the course ID instead of the product title.

**Comment by clintonb** [comment]
@rlucioni updated.

**Comment by rlucioni** [comment]
A heavy-hearted :+1: .

**Pull request merged**
