### PR TITLE
Can't edit course two times

### PR DESCRIPTION
**Pull request by iivic**
LEARNER-1293

@edx/helio This should fix the issue of editing a course two times in a row. But a few flaky tests appeared after this fix (three to be precise). I don't want to merge until this is resolved but I didn't find a solution yet. I will fix other issues at hand and then return to this one if someone doesn't find a solution in the mean time.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1308&repo=edx%2Fecommerce"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by clintonb** [comment]
This issue was introduced by https://github.com/edx/ecommerce/pull/1288.

**Review by mjfrey — APPROVED** [review]

**Comment by iivic** [comment]
@clintonb I would like to merge this if you're fine with it.

**Review by clintonb — APPROVED** [review]
Please provide some context in your commit message. The commit message tells a story—what changed and why. That story is incomplete in this commit message. 

Based on your comments it HipChat, you are not really sure why this is broken. At the very least your commit title should be something along the lines of: Fixed bug in CAT that prevented courses from being updated multiple times. This at least tells me why this commit is necessary.

**Pull request merged**
