### PR TITLE
WL-468, WL-455: Message Bar and Discount link for bulk purchase removed

### PR DESCRIPTION
**Pull request by malikshahzad228**

### CODE REVIEW

**Comment by malikshahzad228** [comment]
@mattdrayer @saleem-latif 

PR in Mit Theme: https://github.com/edx/edx-themes/pull/30

**Comment by mattdrayer** [comment]
👍

**Comment by vkaracic** [comment]
@mattdrayer this is something to look out for when multiple purchases is enabled/supported. When a user buys a seat and enrollment codes s/he should be able to enter a discount for the seat.

**Comment by malikshahzad228** [comment]
@mattdrayer Should I merge this PR, and make a new Jira story to track the multiple purchases enabled/supported case? on which Vedran pointed.

**Comment by mattdrayer** [comment]
Yes, we do not currently support multiple basket items, but when we do
we'll need to support coupon code entry -- logging a ticket would be good
-- @vkaracic, which JIRA project/epic?
On May 24, 2016 03:50, "Malik Shahzad" notifications@github.com wrote:

@mattdrayer https://github.com/mattdrayer Should I merge this PR, and
make a new Jira story to track the multiple purchases enabled/supported
case? on which Vedran pointed.

**Comment by vkaracic** [comment]
You can log it under SOL / CODES: Redemption Flow.

**Comment by saleem-latif** [comment]
👍

**Comment by malikshahzad228** [comment]
@mattdrayer @vkaracic 

Story is logged: https://openedx.atlassian.net/browse/SOL-1813

**Pull request merged**
