### PR TITLE
Remove last remaining bulk calls to catalog service.

### PR DESCRIPTION
**Pull request by mjfrey**
No longer need to call the catalog service and get all results back for a query.  This is done via page requests.

### CODE REVIEW

**Comment by mjfrey** [comment]
@vkaracic @marjev

**Comment by marjev** [comment]
👍

**Comment by vkaracic** [comment]
The changes look good to me, I'm just curious if we should leave a comment in the `all_products` that it doesn't include seats from the course discovery?

:+1:

**Comment by marjev** [comment]
@mjfrey I've added all the changes to my PR so that we have all this in a single commit.

Can you verify that this PR can be closed in favor of #937?

**Pull request closed without merging**
