### PR TITLE
Fix the URL of trusted Oauth2 providers

### PR DESCRIPTION
**Pull request by ilozano2**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ilozano2! I've created [OSPR-1707](https://openedx.atlassian.net/browse/OSPR-1707) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/ecommerce/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by gsong** [comment]
@ilozano2 Can you rebase this onto the current `master`? Thank you.

**Comment by ilozano2** [comment]
Sorry, I will rebase on master and force a push to my branch

**Comment by ilozano2** [comment]
@gsong the branch is updated. Sorry for the name (github put this name automatically when you apply the change on the browser).

**Comment by cahrens** [comment]
@gsong This branch still seems to have problems. I am going to mark this OSPR "Waiting on Author".

**Comment by clintonb** [comment]
We require all branches to be rebased before merging. This works great for internal developers moving at the same pace, but not so much for open source. I have relaxed this requirement.

@ilozano2 please rebase and squash your commit down to a single commit.

**Comment by clintonb** [comment]
We have restored the restriction to avoid past issues with out-of-date branches being merged. I rebased the original commit, and will merge once the build passes.

**Comment by gsong** [comment]
@clintonb Good to go!

**Pull request merged**
