### PR TITLE
ECOM-1807 new attribute for the credit-provider.

### PR DESCRIPTION
**Pull request by awais786**
Add thumbnail url field for the credit provider.

### CODE REVIEW

**Comment by awais786** [comment]
@clintonb please review this PR.

**Comment by clintonb** [comment]
@wedaly we discussed making this a provider attribute (instead of product). Is that no longer the case?

**Comment by wedaly** [comment]
@clintonb No, it's still the case -- it's just that we had that discussion yesterday afternoon :)

@awais786 After talking this over with Clinton, we think it makes more sense to store the image URL with the credit provider in the LMS.  This will allow us to re-use the same image for all credit seats from the same provider; we also get the benefit of using an asset pipeline / CDN that's already set up.

Unfortunately, I think this is a scope change.  Could you please move the subtask you created into its own story so we can point it at our next grooming meeting?  My apologies for the miscommunication.

**Comment by awais786** [comment]
@wedaly, @clintonb closing this PR.

**Pull request closed without merging**
