### PR TITLE
Upgrade gunicorn and gevent

### PR DESCRIPTION
**Pull request by rlucioni**
Byproduct of ECOM-5386.

@jibsheet @edx/ecommerce

### CODE REVIEW

**Comment by jibsheet** [comment]
:+1: although I'll want to read changelogs once I'm back at a keyboard.  We should consider shipping this as a configuration only deploy.

**Comment by clintonb** [comment]
👍

**Comment by jibsheet** [comment]
Finished my changelog read, I definitely like the improvements.

**Comment by rlucioni** [comment]
@jibsheet great, thanks for taking a look. What do you mean by a configuration-only deploy? Should I not merge this to master?

**Comment by jibsheet** [comment]
I think you can merge safely, I just wonder if we should
cut ami for ecommerce ... with configuration=master
and not update ecom/secure - that way there's a quick deploy with just the gunicorn bump.  We should be able to do that prior to the management command release, depending on Solutions planned release cadence (I'm not sure what they have stage now).

**Comment by rlucioni** [comment]
Understood.

**Comment by jibsheet** [comment]
@rlucioni Unfortunately, this is breaking CI (fails to start the gunicorn process on the CI sandbox)
http://jenkins.edx.org:8080/job/ansible-provision-continuous-integration/31462/console (less useful since the errors are in the startup log, I've pasted them below).

```
[2016-08-31 13:04:39 +0000] [19355] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/edx/app/ecommerce/ecommerce/ecommerce/wsgi.py", line 30, in <module>
    application = get_wsgi_application()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    django.setup()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/edx/app/ecommerce/ecommerce/ecommerce/courses/models.py", line 17, in <module>
    from ecommerce.courses.publishers import LMSPublisher
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/edx/app/ecommerce/ecommerce/ecommerce/courses/publishers.py", line 17, in <module>
    Product = get_model('catalogue', 'Product')
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/oscar/core/loading.py", line 247, in get_model
    import_module('%s.%s' % (app_config.name, MODELS_MODULE_NAME))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/edx/app/ecommerce/ecommerce/ecommerce/extensions/catalogue/models.py", line 4, in <module>
    from oscar.apps.catalogue.abstract_models import AbstractProduct, AbstractProductAttributeValue
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/oscar/apps/catalogue/abstract_models.py", line 32, in <module>
    'catalogue.managers', ['ProductManager', 'BrowsableProductManager'])
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/oscar/core/loading.py", line 100, in get_classes
    local_module = _import_module(local_module_label, classnames)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/oscar/core/loading.py", line 121, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named managers
[2016-08-31 13:04:39 +0000] [19355] [INFO] Worker exiting (pid: 19355)
Traceback (most recent call last):
  File "/edx/app/ecommerce/venvs/ecommerce/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 218, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 331, in halt
    self.stop()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 381, in stop
    time.sleep(0.1)
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 231, in handle_chld
    self.reap_workers()
  File "/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 506, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

**Comment by rlucioni** [comment]
@jibsheet taking a look.

**Comment by rlucioni** [comment]
@jibsheet testing a fix at http://jenkins.edx.org:8080/job/ansible-provision-continuous-integration/31470/.

**Comment by rlucioni** [comment]
That build failed. This failure looks Oscar-specific, and it's tied to this import: https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/catalogue/abstract_models.py#L32-L33.

**Comment by rlucioni** [comment]
Going further, this seems to be due to the way gevent wraps Python's `__import__` functionality: https://github.com/gevent/gevent/blob/master/src/gevent/builtins.py#L69-L98.

**Pull request merged**
