### PR TITLE
Revert of fix-e2e-timeout

### PR DESCRIPTION
**Pull request by Ayub-Khan**
LEARNER-5681
Timeout duration was not the issue.
Creating new pr to fix the comment.

### CODE REVIEW

**Comment by tasawernawaz** [comment]
@Ayub-Khan Do we have any related ticket ? If yes, please mention it.

**Review by tasawernawaz — APPROVED** [review]

**Comment by Ayub-Khan** [comment]
@robrap kindly merg this to reset the timeout to 60.

**Comment by Ayub-Khan** [comment]
@tasawernawaz  my bad here is the ticket link https://openedx.atlassian.net/browse/LEARNER-5681

**Comment by Ayub-Khan** [comment]
thanks

**Pull request merged**
