### PR TITLE
Updated receipt page

### PR DESCRIPTION
**Pull request by clintonb**
- Updated verification message, removing reference to single course
- Receipt page now displays discounts for non-voucher-based offers

LEARNER-332

### CODE REVIEW

**Comment by clintonb** [comment]
Prior to this change the receipt page did not display all conditional offer discounts, only those associated with vouchers.

**Voucher Discount**
screencapture-localhost-18130-checkout-receipt-1491059825132

**Conditional Offer**
screencapture-localhost-18130-checkout-receipt-1491059815590

**Comment by clintonb** [comment]
@edx/helio please review

**Review by mjfrey — APPROVED** [review]

**Comment by vkaracic** [comment]
Should UX review this as well?

**Comment by clintonb** [comment]
Review for one new line item? Nah. I feel confident in pushing this as-is. If we need to iterate later, we can.

**Review by vkaracic — APPROVED** [review]
Coolio

**Pull request merged**
