### PR TITLE
Get info from order directly not via the basket

### PR DESCRIPTION
**Pull request by mjfrey**
Go directly to the order lines rather than via basket to get a match.

### CODE REVIEW

**Comment by mjfrey** [comment]
FYI @vkaracic

**Comment by mjfrey** [comment]
@mattdrayer @rlucioni can you take a look?

**Comment by mattdrayer** [comment]
This seems like a valid change to me -- I can't see why we would want to traverse the basket model to get from the order to the line, but perhaps @vkaracic has some insight to lend here.

+1 for me and good to merge once all checks/tests are passing.

**Comment by rlucioni** [comment]
👍

**Comment by vkaracic** [comment]
@mattdrayer I too just today found out that you can access the lines in an order directly, can't remember why this was implemented that way. Oscar is a mysterious beast.

:+1:

**Pull request merged**
