### PR TITLE
add documentation for using CAT locally

### PR DESCRIPTION
**Pull request by adampalay**
@peter-fogg  , may you please take a first pass — this PR adds documentation for setting up CAT to work on devstack

### CODE REVIEW

**Comment by adampalay** [comment]
I have no idea why the test that failed did, since I didn't touch any code.

**Comment by peter-fogg** [comment]
@adampalay Looks good, thanks for doing this! :+1: I'm pretty sure that's a flaky test -- I'll file a ticket for it.

**Comment by adampalay** [comment]
Thanks @peter-fogg , what's the method to rerunning a test with travis?

@rlucioni , may you please take a look too?

**Comment by peter-fogg** [comment]
@adampalay I don't think we have a hook set up for Travis, so you should probably just rebase + push.

**Comment by vkaracic** [comment]
@adampalay there is a rebuild button on Travis where you can re-run the test. I've re-ran it for you.

**Comment by adampalay** [comment]
thanks @vkaracic

**Comment by clintonb** [comment]
:+1:

**Comment by rlucioni** [comment]
Thanks for your contribution @adampalay, :+1: .

**Comment by adampalay** [comment]
thanks team!

**Pull request merged**
