### PR TITLE
[SOL-1707] Checkout Page UX Improvements

### PR DESCRIPTION
**Pull request by marjev**
@mjfrey Please take a look at the code.

JIRA ticket: [SOL-1707](https://openedx.atlassian.net/browse/SOL-1707)

@pbaruah, below are the screenshots that show the changes and the current state of the pages. Let me know if you have any changes you would like me to make. Thanks!

Enrollment code offer redemption page:
screen shot 2016-04-06 at 10 41 17

Discount code offer redemption page:
screen shot 2016-04-06 at 10 41 48

Basket (Checkout) page:
screen shot 2016-04-06 at 10 41 58

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @marjev! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=662&repo=edx%2Fecommerce

**Comment by pbaruah** [comment]
@marjev - In the basket page, can we say "Coupon code ABCD applied" instead of "Promotion code ABCD applied"?

**Comment by marjev** [comment]
@pbaruah Here's the latest screenshot:

screen shot 2016-04-07 at 09 03 47

**Comment by pbaruah** [comment]
👍

**Pull request merged**
