### PR TITLE
Disable apply voucher button during submit.

### PR DESCRIPTION
**Pull request by waheedahmed**
Stop concurrent requests by disabling submit button during submission.

PROD-301

### CODE REVIEW

**Comment by cpennington** [comment]
Does the voucher button need to be re-enabled when the call to apply it returns?

Also, it would be great to disable the payment submit button while applying a voucher as well, not having that has caused some order discrepancies recently. Is that something you'd be willing to add on to this PR?

**Comment by waheedahmed** [comment]
@cpennington No, it doesn't need to be re enabled because whole page reloaded again upon this request which automatically enables the apply button.

Sure, I'll add the disable functionality for payment button as well.

**Comment by robrap** [comment]
Note that there are two ways to pay, including PayPal, and both would need to be disabled.

**Comment by waheedahmed** [comment]
@cpennington @robrap I have updated the PR kindly take another look.

**Review by cpennington — APPROVED** [review]

**Review by adeelkhan — APPROVED** [review]

**Pull request merged**
