### PR TITLE
Fixed lingering issues with the CourseListView

### PR DESCRIPTION
**Pull request by Nickersoft**
Fixed unaddressed issues with #148 

@clintonb

### CODE REVIEW

**Comment by clintonb** [comment]
:+1:

**Comment by clintonb** [comment]
@Nickersoft in the future please wait for the build to finish before merging.

**Comment by Nickersoft** [comment]
@clintonb It did finish.. the merge button was green when I merged.

**Comment by Nickersoft** [comment]
@clintonb I'll double check to be sure. The most recent commit said it errored despite my claim.

**Comment by clintonb** [comment]
The merge button does not indicate build status. A green checkmark beside the commit indicates build status. In this case, you have a build error.

**Comment by Nickersoft** [comment]
@clintonb Okay. I'll investigate.

**Pull request merged**
