### PR TITLE
ENT-4263: Exclude Refunded Enrollments from user bookings limit

### PR DESCRIPTION
**Pull request by sameenfatima78**
## Description

Describe what this pull request changes, and why these changes were made. How will these changes affect other people, installations of edx, etc.?
Please include links to any relevant ADRs, design artifacts, and decision documents. Make sure to document the rationale behind significant changes in the repo, per [OEP-19](https://open-edx-proposals.readthedocs.io/en/latest/oep-0019-bp-developer-documentation.html), and can be
linked here.

Useful information to include:
- Which edX user roles will this change impact? Common user roles are "Learner", "Course Author", "Developer", and "Operator".
- Include screenshots for changes to the UI (ideally, both "before" and "after" screenshots, if applicable).
- Provide links to the description of corresponding configuration changes. Remember to correctly annotate these changes.

## Supporting information

Link to other information about the change, such as Jira issues, GitHub issues, or Discourse discussions.
Be sure to check they are publicly readable, or if not, repeat the information here.

## Testing instructions

Please provide detailed step-by-step instructions for testing this change; how did YOU test this change?

## Other information

Include anything else that will help reviewers and consumers understand the change.
- Does this change depend on other changes elsewhere?
- Any special concerns or limitations? For example: deprecations, migrations, OpenEdx vs. edx.org differences, development vs. production environment differences, security, or accessibility.

### CODE REVIEW

**Review by moconnell1453 — APPROVED** [review]
LGTM! One nit: Can we organize our 'objects' method calls into separate lines? It would make it easier to read, and in reviews like this, it would appear as just one new line in the list of operations. e.g.:

        refunded_order_ids = self._get_refunded_order_ids()
        max_order_count_any_user = OrderDiscount.objects.filter(offer_id=self.instance.id)
	.select_related('order')
	.filter(order__status=ORDER.COMPLETE)
	.exclude(order_id__in=refunded_order_ids)
	.values('order__user_id')
	.order_by('order__user_id')
	.annotate(count=Count('order__id'))
	.aggregate(Max('count'))['count__max'] or 0

I'd like to have a best practices guide to point to that reinforces (or refutes it in the case that I am wrong).

**Review by irfanuddinahmad — APPROVED** [review]
LGTM!

**Review by saleem-latif — APPROVED** [review]
Looks Good 👍

**Comment by sameenfatima78** [comment]
> LGTM! One nit: Can we organize our 'objects' method calls into separate lines? It would make it easier to read, and in reviews like this, it would appear as just one new line in the list of operations. e.g.:
> 
> ```
>     refunded_order_ids = self._get_refunded_order_ids()
>     max_order_count_any_user = OrderDiscount.objects.filter(offer_id=self.instance.id)
> .select_related('order')
> .filter(order__status=ORDER.COMPLETE)
> .exclude(order_id__in=refunded_order_ids)
> .values('order__user_id')
> .order_by('order__user_id')
> .annotate(count=Count('order__id'))
> .aggregate(Max('count'))['count__max'] or 0
> ```
> 
> I'd like to have a best practices guide to point to that reinforces (or refutes it in the case that I am wrong).

@moconnell1453 Good suggestion! I actually did try this coding-style when I was making the changes but the IDE started throwing errors so I couldn't go forward with this style.

**Pull request merged**
