### PR TITLE
Add AliPay processor.

### PR DESCRIPTION
**Pull request by MengqiYe**
Tested on live mode, with api_alipay_trade_page_pay, to checkout.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @seaswander! I've created [OSPR-2000](https://openedx.atlassian.net/browse/OSPR-2000) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/ecommerce/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Review by clintonb — CHANGES_REQUESTED** [review]
`alipay_sdk` should be a third-party library, not stored in this repo. Additionally, all payment code needs to be fully tested and the processor needs to work with client-side checkout.

**Comment by nedbat** [comment]
@seaswander We need to have a signed contributor's agreement from you before we can work with this pull request.  Clinton has given you some large-scale feedback that will need to be followed also.

**Comment by clintonb** [comment]
See https://github.com/edx/ecommerce/pull/1602 for an implementation using Stripe.

**Comment by nedbat** [comment]
@seaswander Are you interested in pursuing this?

**Comment by nedbat** [comment]
@seaswander I'm going to close this since we haven't heard from you in a while.  Feel free to re-open it if you come back to it.

**Comment by openedx-webhooks** [comment]
@seaswander Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/ecommerce&entry.867055334=https://github.com/edx/ecommerce/pull/1561&entry.1484655318=https://github.com/seaswander&entry.752974735=2017-11-09+11:32&entry.1917517419=2018-01-24+19:51&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
