### PR TITLE
Fix ADR links.

### PR DESCRIPTION
**Pull request by waheedahmed**
This ADR was abandoned long time back, due to which `0003` was occupied by another ADR. Also updated the links.

### CODE REVIEW

**Review by adeelkhan — APPROVED** [review]

**Review by adeelkhan — APPROVED** [review]

**Comment by waheedahmed** [comment]
@robrap Just noticed there is another ADR with this same number `0003`.

**Comment by robrap** [comment]
@waheedahmed: Feel free to put up a new PR to adjust the number.  Feel free to get anyone to thumb it.

**Comment by robrap** [comment]
Oops. I missed that this was already the PR with the rename. Sorry. :)

**Comment by waheedahmed** [comment]
@robrap Sure, Thanks!

**Review by robrap — APPROVED** [review]

**Pull request merged**
