### PR TITLE
Audit logging tweaks

### PR DESCRIPTION
**Pull request by rlucioni**
Simplify audit logging utility, log order_placed message prior to order fulfillment, and include course ID and certificate type in messages logged by the EnrollmentFulfillmentModule. XCOM-426.

@jimabramson or @clintonb, I'd appreciate a review when you get a chance.

### CODE REVIEW

**Comment by jimabramson** [comment]
@rlucioni code lgtm; my one question is whether the course key and cert type attribute lookups are incurring database hits that would otherwise not be.  if that's the case i think we should be sure the additional attributes in the logs justify the additional work.

**Comment by rlucioni** [comment]
@jimabramson I've made a slight change so that including these additional attributes in the log messages results in no additional work. The course key and certificate type attributes are retrieved once and cached in process, during both fulfillment and revocation.

**Comment by jimabramson** [comment]
:+1: good stuff

**Comment by clintonb** [comment]
:+1:

**Pull request merged**
