### PR TITLE
Switch to segment analytics-python from edx fork

### PR DESCRIPTION
**Pull request by BenjiLee**
@bderusha Is this the fork change you are looking for?

### CODE REVIEW

**Review by feanil — APPROVED** [review]

**Comment by feanil** [comment]
For reference: we're going to ship this along with https://github.com/edx/configuration/pull/4415 and https://github.com/edx/edx-internal/pull/332

**Comment by BenjiLee** [comment]
There seems to be an isort issue on master? No idea why it's surfacing in this PR. 

The fix for that is here https://github.com/edx/ecommerce/pull/1684. Once merge, I will rebase this PR.

**Review by bderusha — APPROVED** [review]

**Comment by bderusha** [comment]
@BenjiLee I believe the isort issue is because it's treated differently as a package install VS github install.  So isort wants it in a different group

**Comment by bderusha** [comment]
:shipit: 👍

**Pull request merged**
