### PR TITLE
Updated the provider selection to trigger the change event

### PR DESCRIPTION
**Pull request by aamir-khan**
ECOM-3900
Updated the javascript to trigger the change event on checkout page. 
@awaisdar001 @Shrhawk @mushtaqak @Qubad786 @Ayub-Khan @attiyaIshaque Please review this PR.

### CODE REVIEW

**Comment by mushtaqak** [comment]
@aamir-khan Should we not write any test for this ?

**Comment by aamir-khan** [comment]
@adampalay Please review this PR.

**Comment by adampalay** [comment]
@aamir-khan , echoing @mushtaqak , can you please write a test?

**Comment by aamir-khan** [comment]
@mushtaqak @adampalay For writing the tests I created ECOM-4291. Please review this PR now.

**Comment by aamir-khan** [comment]
@clintonb Can you please review this PR.

**Comment by clintonb** [comment]
Why is this necessary? Also, tests should be included with this PR, not as follow-up work.

**Comment by aamir-khan** [comment]
@clintonb The issue is when the user clicks the back button of browser from the payment page to come back to this credit checkout page the first provider has already been selected and provider change event does not triggered. This change event basically sets the _Total Price_ value. I just cleared the checked button before clicking the first provider. This trigger the change event of provider's radio button and sets the Total Price value.

For tests there are no acceptance tests written for this credit checkout page. The credit checkout page on ecommerce makes an ajax call to LMS to check that the user has passed the course and also is eligible for the credit. I could not find the tests related to this i.e passing the credit course and fulfilling all credit eligibility requirement. I discussed with @adampalay and created ECOM-4291 for writing the tests for credit courses from scratch.

**Pull request closed without merging**
