### PR TITLE
Added verbosity to pip requirements installation

### PR DESCRIPTION
**Pull request by clintonb**
I have removed the quiet argument so that we can see exactly what is installed when this command is called. This is primarily useful for knowing what is installed by Travis.

### CODE REVIEW

**Comment by clintonb** [comment]
FYI @edx/ecommerce @marjev

**Comment by marjev** [comment]
@clintonb Check this out: https://gist.github.com/tristandostaler/2f8b28f2bf503db4422a5549e8fed538

Not sure if that will help, but might be a good starting point. If we plan to update the Selenium and Firefox versions, looks like a way to go.
Also, official documentation: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

**Comment by clintonb** [comment]
@marjev nice find! My latest fixup commit incorporates that new knowledge. Here's hoping it resolves the issue!

**Comment by marjev** [comment]
🎆 It works!! 🍾

**Pull request merged**
