### PR TITLE
Remove duplicate code

### PR DESCRIPTION
**Pull request by WeJie**
Already had the `BasketAttribute.objects.get()` method beneath the code I remove.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @WeJie! I've created [OSPR-2811](https://openedx.atlassian.net/browse/OSPR-2811) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@WeJie Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by WeJie** [comment]
I have sent the email. @natabene :)

**Comment by natabene** [comment]
@WeJie  Great, thank you. It will take our team a few days to process, after which you will be notified once you are all set.

**Comment by natabene** [comment]
@nedbat  Do you want to have a look?

**Review by robrap — APPROVED** [review]
Thanks for this.  I did add [a comment](https://github.com/edx/ecommerce/commit/9da1dc876d21a7dbadfd3c95a732fbe4aa3b4d1e#r31502508) for @saleem-latif here to try to understand why this was added.  Your PR seems reasonable to me.

**Comment by natabene** [comment]
@robrap  Do you want to merge it?

**Comment by robrap** [comment]
@natabene: I can take care of merge, but it needs to be rebased immediately before merging, and then I need to be able to deploy to Production, and I might not be able to get to that until next week.  Also, I wanted to give a little time to hear back from the engineer who added this code.

**Comment by natabene** [comment]
@robrap  Got it, thanks for clarifying!

**Review by saleem-latif — APPROVED** [review]
👍 @WeJie thanks for looking into this

**Comment by openedx-webhooks** [comment]
@WeJie 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/ecommerce&entry.867055334=https://github.com/edx/ecommerce/pull/1984&entry.1484655318=https://github.com/WeJie&entry.752974735=2018-11-17+08:25&entry.1917517419=2018-12-20+21:15&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
