### PR TITLE
HON-93 Add payment_support_url field to SiteConfiguration model to allow for…

### PR DESCRIPTION
**Pull request by douglashall**
… customization of this URL by Site.

Related PR for removal of setting from configuration repo: https://github.com/edx/configuration/pull/3390

Related DevOps ticket for removal of setting overrides from configuration_secure: https://openedx.atlassian.net/browse/DEVOPS-4807

### CODE REVIEW

**Comment by douglashall** [comment]
@mjfrey Would you be able to review this?

**Comment by mjfrey** [comment]
LGTM
👍

**Comment by vkaracic** [comment]
Should this field be added in the `create_or_update_site` management command?

**Comment by douglashall** [comment]
@vkaracic Sure. [Here](https://github.com/edx/ecommerce/pull/948) is a PR. Please review.

**Pull request merged**
