### PR TITLE
WAIT-LMS: Using order number for receipt page

### PR DESCRIPTION
**Pull request by clintonb**
The updated receipt page relies on order numbers, not basket IDs.

ECOM-2653

### CODE REVIEW

**Comment by clintonb** [comment]
Depends on edx/edx-platform#10349.

**Comment by jimabramson** [comment]
nitpick:  why the switch to camelCase ?

**Comment by clintonb** [comment]
@jimabramson personal preference. Don't get too attached. This page will ultimately die once we move it to Otto.

**Comment by bderusha** [comment]
:+1: lgtm

**Comment by cpennington** [comment]
Do we have a consistent style for url parameters? We should pick one, and stick with it.

**Comment by rlucioni** [comment]
FWIW, we tend to use underscores instead of camelCase elsewhere. :+1: otherwise. Let's make sure this isn't deployed before https://github.com/edx/edx-platform/pull/10349.

**Comment by clintonb** [comment]
Neither the team nor edX has a style for query string parameters. Ultimately, I don't even want to use querystring parameters. I want `https://ecommerce.edx.org/orders/EDX-1234/`.

**Pull request merged**
