### PR TITLE
fix: same title for Cybersource and LiqPay buttons for legacy

### PR DESCRIPTION
**Pull request by DmytroAlipov**
This is a backport from [master](https://github.com/openedx/ecommerce/pull/4009)

## Description

For the legacy page of the course payment selection, there is a scenario when we have two Checkout buttons. It is not clear what payment they are intended for.

cybersource_liqpay_buttons

This is how it looks after fixing:

screen_32

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @DmytroAlipov! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @colinbrash and @openedx/revenue-squad! Could someone please review/merge this for us? Thanks!

**Comment by nedbat** [comment]
This is a merge into Palm.  The BTR group can review and merge it.

**Comment by mphilbrick211** [comment]
> This is a merge into Palm. The BTR group can review and merge it.

@nedbat hi there! Just following up to see if this can be merged?

**Pull request closed without merging**
