### PR TITLE
[BB-3801] feat: install extra requirements in the tox environments

### PR DESCRIPTION
**Pull request by lgp171188**
This PR adds a `requirements/extra.txt` requirement file and configures `tox` to install them in its environments.

## Description

Extra requirements for ecommerce specified via the `ECOMMERCE_EXTRA_REQUIREMENTS` ansible variable in the `edx/configuration` repository do not get installed in the `tox` environments used to run the migrations (`make migrate`).

This is necessary when the extra requirements are added to

`INSTALLED_APPS` and hence have to be installed in the `tox` virtualenv
environments used for the various Django management commands.

This PR is related to and depends on https://github.com/edx/configuration/pull/6489

**Testing instructions**:

## Testing instructions

* Add some extra requirements (for example, `git+https://github.com/open-craft/ecommerce-hyperpay.git#egg=hyperpay-ecommerce`) to `requirements/extra.txt` and add them to `INSTALLED_APPS (for example, `hyperpay`).
* Run `make migrate` in as the `ecommerce` user in the ecommerce environment.
* Verify that the specified extra requirements are installed in the `tox` environment and the migration command completes successfully.

## Reviewers
- [ ] @kaizoku 
- [ ] edX reviewers (TBD)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @lgp171188!  I've created [OSPR-5936](None/browse/OSPR-5936) to keep track of it in JIRA, where we prioritize reviews.  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

**Comment by kaizoku** [comment]
:+1:

- [✓] I tested this: (checked that tox installs extra requirements)
- [✓] I read through the code
- [n/a] ~~I checked for accessibility issues~~
- [✓] Includes documentation

**Comment by natabene** [comment]
@lgp171188 Thank you for your contribution. Please let me know once this is ready for our review.

**Comment by lgp171188** [comment]
@natabene, this is ready for edX review.

**Comment by gabor-boros** [comment]
@natabene is there anything we could do to help you push this forward? 😇

**Comment by natabene** [comment]
@gabor-boros Not yet, we are considering how we can make this happen. Please stay tuned.

**Review by pshiu — APPROVED** [review]
Hey @lgp171188, thanks for your contribution! This looks good to me, sorry for the extended delay. Could you rebase/merge master in please?

**Comment by natabene** [comment]
@lgp171188 Once you rebase and fix any conflicts, should they arise, we will be able to merge.

**Comment by gabor-boros** [comment]
@farhaanbukhsh FYI as you are the assignee of BB-3801

**Comment by lgp171188** [comment]
@natabene, I no longer work for OpenCraft and this PR was created related to some work that I did when I worked there. Like @gabor-boros mentioned (thanks!), @farhaanbukhsh should be able to provide an update on this and take this forward.

**Comment by farhaanbukhsh** [comment]
@gabor-boros @lgp171188  Ack!

**Comment by natabene** [comment]
@farhaanbukhsh Can you let me know if you plan to pursue this PR further (rebase and fix conflicts)?

**Comment by farhaanbukhsh** [comment]
> @farhaanbukhsh Can you let me know if you plan to pursue this PR further (rebase and fix conflicts)?

I have planned some time this sprint  to rebase it :)

**Comment by farhaanbukhsh** [comment]
@natabene  I have rebased the PR, should I re-open the PR?

**Comment by pshiu** [comment]
Sorry for the bureaucracy, @farhaanbukhsh, but our CLA bot is blocking the PR noting that we seem to still need a CLA from you. Have you filled out [the CLA application](https://tcril.tfaforms.net/f/individual-cla) yet?

**Comment by farhaanbukhsh** [comment]
@pshiu I think it is blocking because of @lgp171188's CLA, should I re-open the PR?

**Comment by pshiu** [comment]
Ah, apologies @farhaanbukhsh, you're right, it's because of @lgp171188's CLA. Yes, please re-open and tag me as a reviewer!

**Comment by lgp171188** [comment]
> Sorry for the bureaucracy, @farhaanbukhsh, but our CLA bot is blocking the PR noting that we seem to still need a CLA from you. Have you filled out the CLA application yet?

@pshiu, this PR was covered by OpenCraft's CLA when I created it, since I was working for OpenCraft at that time. @farhaanbukhsh is now the owner of this PR. But if I have to sign the CLA to help push this forward, I am happy to do that.

**Comment by natabene** [comment]
@lgp171188 Thanks for chiming in. We don't need you to sign the CLA again. What is happening is that the OSPR bot has no historical memory unfortunately, so situation like these occur. We are good for now.

**Comment by natabene** [comment]
@farhaanbukhsh Please let me know once  you re-open so I can close this one.

**Comment by natabene** [comment]
@farhaanbukhsh When you reopen please reference this PR so we can get background context from it.

**Comment by natabene** [comment]
@farhaanbukhsh Actually, if you are not planning to re-open this from under your name, can I close this for now? So it is off our radar and we know a review is not needed.

**Comment by farhaanbukhsh** [comment]
@natabene I am really sorry for the delay. I have opened another PR , please feel free to close this PR.

**Comment by openedx-webhooks** [comment]
@lgp171188 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/ecommerce&entry.867055334=https://github.com/openedx/ecommerce/pull/3478&entry.1484655318=https://github.com/lgp171188&entry.752974735=2021-07-26+15:11&entry.1917517419=2022-10-21+15:25&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
