### PR TITLE
fix: upstream rtl changes

### PR DESCRIPTION
**Pull request by meysam81**
I'm not sure whether or not I followed the instructions correctly from [here](https://tasks.opencraft.com/secure/EditComment!default.jspa?id=36995&commentId=223062).

But I applied the steps, and the following screenshot is the result of that effort:

screenshot

reviewer @giovannicimolin

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @meysam81! I've created [OSPR-6076](https://openedx.atlassian.net/browse/OSPR-6076) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@meysam81 Thank you for your contribution. Let's see how check turn out.

**Comment by giovannicimolin** [comment]
@natabene Can you close this pull request? We're not pursuing this anymore.

**Comment by openedx-webhooks** [comment]
@meysam81 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/ecommerce&entry.867055334=https://github.com/edx/ecommerce/pull/3522&entry.1484655318=https://github.com/meysam81&entry.752974735=2021-09-28+09:20&entry.1917517419=2021-12-08+19:35&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
