### PR TITLE
Removed devstack overrides

### PR DESCRIPTION
**Pull request by clintonb**
- Retrieving base settings from configuration
- Allowing for local overrides in private.py

### CODE REVIEW

**Comment by clintonb** [comment]
@feanil @jibsheet 

FYI @rlucioni @jimabramson @bderusha @peter-fogg

**Comment by rlucioni** [comment]
@clintonb what's the impetus for removing the JWT and API key overrides? The way it's currently structured allows these settings to be configured by using the configuration file on disk.

**Comment by clintonb** [comment]
@rlucioni `JWT_AUTH` is specified in configuration so there is no need for it to be updated/redefined. If overrides are necessary they should be in `private.py`.

**Comment by rlucioni** [comment]
Got it, thanks. Good catch on the logging configuration, too. :+1:

**Comment by feanil** [comment]
:+1:

**Pull request merged**
