### PR TITLE
Upgrade Django to 1.9.13

### PR DESCRIPTION
**Pull request by rlucioni**
@edx/learner FYI

### CODE REVIEW

**Review by clintonb — APPROVED** [review]

**Comment by rlucioni** [comment]
Since when are ecommerce tests so flaky?

**Comment by clintonb** [comment]
@rlucioni which test? I recently un-skipped a refund test.

**Comment by rlucioni** [comment]
@clintonb I should have made a note; I don't remember which exact tests were failing. One was a JS test. I restarted the build twice and the history seems to be lost. If I see it again I'll make a ticket.

**Comment by rlucioni** [comment]
@clintonb [LEARNER-491](https://openedx.atlassian.net/browse/LEARNER-491).

**Pull request merged**
