### PR TITLE
Fallback to Django settings if site config is empty.

### PR DESCRIPTION
**Pull request by mjfrey**
Try to gett settings from site config and if not there use the Django settings.

### CODE REVIEW

**Comment by mjfrey** [comment]
@douglashall

**Comment by clintonb** [comment]
Why the fallback? I specifically advised against such a fallback to ensure that all sites are configured in the same manner.

**Comment by douglashall** [comment]
Yes, thinking about this more all we need to do is update the SiteConfiguration.oauth_settings field with the correct values for the ecommerce site in stage/prod. I have a story in this sprint to clean up the old settings from configuration and remove the fallback for the Otto login workflow.

**Comment by mjfrey** [comment]
I will work with Doug to update the site configs on stage / prod.

**Pull request closed without merging**
