### PR TITLE
WIP [SOL-1873] Flaky JS tests for coupons

### PR DESCRIPTION
**Pull request by iivic**
I'm not sure if this will fix the issue 
2) should display coupon details in form fields
     coupons edit view edit enrollment code
     Expected '' to equal undefined.
I can't reproduce it locally I'll just test it here if it passes several times I'll assume it's fixed.
@marjev @vkaracic

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @iivic! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=833

**Comment by marjev** [comment]
Seems like we have one more flaky test. See the one that failed and try to fix that as well.

**Comment by iivic** [comment]
Looks good. Waiting for thumbs up.

**Comment by vkaracic** [comment]
LGTM

**Pull request merged**
