### PR TITLE
Remove API constants

### PR DESCRIPTION
**Pull request by marjev**
@mjfrey, @vkaracic Can you please take a look at this? This PR is a part of [SOL-1890](https://openedx.atlassian.net/browse/SOL-1890).

I deleted `api/constants.py`. Since constants found within are used only in coupon API view, those constants should be moved there.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @marjev! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fecommerce&number=898

**Comment by vkaracic** [comment]
:+1:

**Comment by marjev** [comment]
@iivic Take a look.

**Comment by iivic** [comment]
LGTM 👍

**Pull request merged**
